import Link from "next/link"
import { redirect } from "next/navigation"
import { supabaseAdmin } from "@/lib/supabase/admin"
import { getCurrentUser } from "@/lib/workspaces"
import { LeaveWorkspaceForm } from "@/components/account/LeaveWorkspaceForm"
import { acceptWorkspaceInvitation, leaveWorkspace, updateUsername } from "./actions"
import { ProfileSettings } from "@/components/account/ProfileSettings"

type PageProps = { params: Promise<{ username: string }> }
export default async function UserAccountPage({ params }: PageProps) {
 const { username } = await params; const user = await getCurrentUser(); if (!user?.email) redirect("/login")
 const { data: profile } = await supabaseAdmin.from("user_profiles").select("username").eq("user_id", user.id).maybeSingle(); if (!profile) redirect("/login"); if (profile.username !== username) redirect(`/users/${profile.username}`)
 const [{ data: memberships }, { data: invitations }] = await Promise.all([supabaseAdmin.from("workspace_memberships").select("workspace_id, role, workspaces!inner(name, slug, status)").eq("user_id", user.id), supabaseAdmin.from("workspace_invitations").select("id, role, expires_at, workspaces!inner(name, slug)").eq("email", user.email.toLowerCase()).is("accepted_at", null).gt("expires_at", new Date().toISOString())])
 return <main className="min-h-screen bg-neutral-950 px-5 py-8 text-white sm:px-8"><div className="mx-auto max-w-3xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-neutral-400">Betelgeze account</p><h1 className="mt-2 text-3xl font-semibold">@{profile.username}</h1><p className="mt-2 text-sm text-neutral-400">{user.email}</p></div><Link href="/logout" className="rounded-lg border border-neutral-700 px-3 py-2 text-sm">Log out</Link></div><ProfileSettings username={profile.username} email={user.email} action={updateUsername} />{(invitations ?? []).length > 0 && <section className="mt-8"><h2 className="text-xl font-semibold">Workspace invitations</h2><div className="mt-4 space-y-3">{(invitations ?? []).map((invite) => { const workspace = invite.workspaces as unknown as { name: string; slug: string }; return <div key={invite.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-blue-400/30 bg-blue-500/10 p-5"><div><p className="font-medium">{workspace.name}</p><p className="mt-1 text-sm capitalize text-neutral-300">Invited as {invite.role}</p></div><form action={acceptWorkspaceInvitation.bind(null, profile.username)}><input type="hidden" name="token" value={invite.id} /><button className="rounded-lg bg-white px-4 py-2 text-sm font-medium text-black">Accept invite</button></form></div> })}</div></section>}<h2 className="mt-10 text-xl font-semibold">Your workspaces</h2><div className="mt-4 space-y-3">{(memberships ?? []).map((membership) => { const workspace = membership.workspaces as unknown as { name: string; slug: string; status: string }; if (workspace.status !== "active") return null; return <div key={membership.workspace_id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-neutral-800 bg-neutral-900 p-5"><div><Link href={`/dashboard/${workspace.slug}`} className="font-medium hover:underline">{workspace.name}</Link><p className="mt-1 text-sm capitalize text-neutral-500">{membership.role}</p></div><LeaveWorkspaceForm workspaceId={membership.workspace_id} action={leaveWorkspace.bind(null, profile.username)} /></div> })}</div><Link href={`/users/${profile.username}/create-dashboard`} className="mt-7 inline-block text-sm text-neutral-300 underline">Create a dashboard</Link></div></main>
}
