import assert from "node:assert/strict"
import test from "node:test"
import {readFileSync} from "node:fs"
import {createRequire} from "node:module"
import ts from "typescript"
const require=createRequire(import.meta.url),loaded=new Map<string,unknown>()
function load(name:string):Record<string,unknown>{if(loaded.has(name))return loaded.get(name) as Record<string,unknown>;const compiled={exports:{}};const code=ts.transpileModule(readFileSync(`lib/client-portal/${name}.ts`,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function("require","module","exports",code)((p:string)=>p.startsWith("./ghl-")?load(p.slice(2)):require(p),compiled,compiled.exports);loaded.set(name,compiled.exports);return compiled.exports}
const {fetchGhlCalendar}=load('ghl-calendar-provider') as typeof import('../lib/client-portal/ghl-calendar-provider')
const {monthWindow,dateKey,monthDays,shiftMonth}=load('ghl-calendar') as typeof import('../lib/client-portal/ghl-calendar')
const {handlePortalGhlCalendar}=load('ghl-calendar-handler') as typeof import('../lib/client-portal/ghl-calendar-handler')
const credentials={locationId:'location123456789',privateToken:'private-token-synthetic'}
const ownerId='owner1234567890',companyId='company123456789',event={id:'event1234567890',calendarId:'calendar123456789',assignedUserId:ownerId,locationId:credentials.locationId,title:'Consultation',startTime:'2026-09-12T09:00:00-05:00',endTime:'2026-09-12T09:30:00-05:00',appointmentStatus:'confirmed'}
const owner={id:ownerId,name:'Client Owner',isAgencyOwner:true,roles:{locationIds:[credentials.locationId]}}
const binding={companyId,timezone:'America/Chicago',owner:{id:ownerId,name:'Client Owner'}}
function fixture(transform?:(path:string,result:Record<string,unknown>)=>Record<string,unknown>){const calls:URL[]=[];const fetcher:typeof fetch=async(input,options)=>{const url=new URL(String(input));calls.push(url);assert.equal(url.origin,'https://services.leadconnectorhq.com');assert.equal(options?.redirect,'error');let value:Record<string,unknown>=url.pathname.startsWith('/locations/')?{location:{id:credentials.locationId,companyId,timezone:'America/Chicago'}}:url.pathname==='/users/search'?{users:[owner],count:1}:url.pathname==='/calendars/blocked-slots'?{events:[]}:{events:[event]};if(transform)value=transform(url.pathname,value);return Response.json(value)};return{calls,fetcher}}
test('resolves the explicit owner and queries their schedule across booking calendars',async()=>{const f=fixture((_p,v)=>({...v,privateToken:'do not expose'}));const s=await fetchGhlCalendar(credentials,'2026-09',null,f.fetcher);assert.equal(s.events.length,1);assert.equal(s.events[0].start,'2026-09-12T14:00:00.000Z');assert.equal(s.owner.id,ownerId);assert.equal(s.source,'owner-user');assert.equal(f.calls.length,4);for(const call of f.calls.filter(u=>u.pathname.startsWith('/calendars/'))){assert.equal(call.searchParams.get('userId'),ownerId);assert.equal(call.searchParams.has('calendarId'),false)}assert.equal(JSON.stringify(s).includes('privateToken'),false)})
test('bound owner refresh verifies ownership alongside schedule reads with three requests',async()=>{const f=fixture();await fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher);assert.equal(f.calls.length,3);assert.equal(f.calls[0].pathname,'/users/search');assert.equal(f.calls[0].searchParams.get('ids'),ownerId);assert.equal(f.calls.some(u=>u.pathname.startsWith('/locations/')),false)})
test('never guesses an owner from names, admins, business email, or ambiguous matches',async()=>{for(const users of [[{...owner,isAgencyOwner:false}],[owner,{...owner,id:'otherowner123456'}],[{...owner,deleted:true}],[{...owner,roles:{locationIds:['otherlocation123']}}]]){const f=fixture((p,v)=>p==='/users/search'?{users,count:users.length}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',null,f.fetcher),/owner_unavailable/);assert.equal(f.calls.length,2)}})
test('revoked ownership or incomplete user search never publishes a schedule',async()=>{for(const change of [{users:[{...owner,isAgencyOwner:false}],count:1},{users:[owner],count:101}]){const f=fixture((p,v)=>p==='/users/search'?change:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher),/owner_unavailable/)}})
test('wrong locations and cross-user events fail without leaking data',async()=>{for(const change of [{locationId:'otherlocation123'},{assignedUserId:'otherowner123456'}]){const f=fixture((p,v)=>p==='/calendars/events'?{events:[{...event,...change}]}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher),/location/)}})
test('deduplicates records, keeps cancelled appointments, hides private busy titles and excludes deleted records',async()=>{const f=fixture((p,v)=>p==='/calendars/events'?{events:[event,event,{...event,id:'cancelled123456',appointmentStatus:'cancelled'},{...event,id:'deleted1234567',deleted:true}]}:p==='/calendars/blocked-slots'?{events:[{...event,id:'privatebusy123456',title:'Private personal event',notes:'Private notes',startTime:'2026-09-29T00:00:00-05:00',endTime:'2026-09-30T00:00:00-05:00'}]}:v);const s=await fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher);assert.equal(s.events.length,3);assert.equal(s.events.find(e=>e.kind==='busy')?.title,'Busy');assert.equal(s.events.find(e=>e.kind==='busy')?.allDay,true);assert.equal(s.events.some(e=>e.status==='cancelled'),true);assert.equal(JSON.stringify(s).includes('Private'),false)})
test('missing date offsets, permission failures and oversized windows fail explicitly',async()=>{await assert.rejects(fetchGhlCalendar(credentials,'2026-09',null,async()=>new Response('secret',{status:401})),/permissions/);for(const events of [[{...event,startTime:'2026-09-12T09:00:00'}],Array(1001).fill(event)]){const f=fixture((p,v)=>p==='/calendars/events'?{events}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher),/response/)}})
test('calendar dates cover leap years, year changes, and Chicago daylight saving',()=>{assert.equal(shiftMonth('2026-12',1),'2027-01');assert.equal(shiftMonth('2026-01',-1),'2025-12');assert.equal(monthDays('2028-02').includes('2028-02-29'),true);const march=monthWindow('2026-03','America/Chicago');assert.equal(new Date(march.start).toISOString(),'2026-03-01T06:00:00.000Z');assert.equal(new Date(march.end).toISOString(),'2026-04-12T05:00:00.000Z');assert.equal(dateKey('2026-09-13T01:00:00Z','America/Chicago'),'2026-09-12')})
const request=(body:unknown)=>new Request('https://portal.example/calendar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})
test('calendar snapshot GET never contacts GHL and never projects credentials',async()=>{const r=await handlePortalGhlCalendar(new Request('https://portal.example/calendar'),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{assert.equal(p.p_action,'read');return {data:{snapshot:null,privateToken:'secret'},error:null}},fetchCalendar:async()=>{throw Error('must not call')}});assert.deepEqual(await r.json(),{revision:null,snapshot:null,refreshedAt:null,error:null,busy:false});assert.equal(r.headers.get('cache-control'),'private, no-store')})
test('calendar authorization and request validation run before provider or write RPC',async()=>{for(const access of [null,{workspace:{id:'w'}}]){const r=await handlePortalGhlCalendar(request({month:'all-history'}),'token',{resolve:async()=>access,rpc:()=>{throw Error('must not call')}});assert.equal(r.status,access?400:404)}})
test('refresh is leased and failures release only its own operation',async()=>{const actions:string[]=[];const r=await handlePortalGhlCalendar(request({month:'2026-09'}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{actions.push(String(p.p_action));assert.equal(p.p_workspace_id,'w');return {data:p.p_action==='begin'?credentials:{},error:null}},fetchCalendar:async()=>{assert.deepEqual(actions,['begin']);throw Error('private provider payload')}});assert.deepEqual(actions,['begin','fail']);assert.equal(r.status,503);assert.equal(JSON.stringify(await r.json()).includes('private provider'),false)})

test('the browser cannot select a different user or booking calendar',async()=>{for(const field of ['calendarId','userId','owner']){const r=await handlePortalGhlCalendar(request({month:'2026-09',[field]:'someone-else'}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:()=>{throw Error('must not call')}});assert.equal(r.status,400)}})
test('legacy selected-calendar snapshots are hidden during rollout',async()=>{const r=await handlePortalGhlCalendar(new Request('https://portal.example/calendar'),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async()=>({data:{snapshot:{calendarId:'legacy',events:[event]}},error:null})});assert.equal((await r.json()).snapshot,null)})
test('multi-day busy time appears on each covered date, excluding its end midnight',()=>{const {groupCalendarEvents}=load('ghl-calendar') as typeof import('../lib/client-portal/ghl-calendar');const result=groupCalendarEvents([{id:'test',kind:'busy',title:'Busy',start:'2026-09-10T00:00:00-05:00',end:'2026-09-12T00:00:00-05:00',allDay:true,status:'busy'}],'America/Chicago',monthDays('2026-09'));assert.equal(result.get('2026-09-10')?.length,1);assert.equal(result.get('2026-09-11')?.length,1);assert.equal(result.has('2026-09-12'),false)})
