import assert from "node:assert/strict"
import test from "node:test"
import {readFileSync} from "node:fs"
import {createRequire} from "node:module"
import ts from "typescript"
const require=createRequire(import.meta.url),loaded=new Map<string,unknown>()
function load(name:string):Record<string,unknown>{if(loaded.has(name))return loaded.get(name) as Record<string,unknown>;const compiled={exports:{}};const code=ts.transpileModule(readFileSync(`lib/client-portal/${name}.ts`,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function("require","module","exports",code)((p:string)=>p.startsWith("./ghl-")?load(p.slice(2)):require(p),compiled,compiled.exports);loaded.set(name,compiled.exports);return compiled.exports}
const {fetchGhlCalendar}=load('ghl-calendar-provider') as typeof import('../lib/client-portal/ghl-calendar-provider')
const {monthWindow,dateKey,monthDays,shiftMonth}=load('ghl-calendar') as typeof import('../lib/client-portal/ghl-calendar')
const {handlePortalGhlCalendar}=load('ghl-calendar-handler') as typeof import('../lib/client-portal/ghl-calendar-handler')
const credentials={locationId:'location123456789',privateToken:'private-token-synthetic'}
const cal='calendar123456789',event={id:'event1234567890',calendarId:cal,locationId:credentials.locationId,title:'Consultation',startTime:'2026-09-12T09:00:00-05:00',endTime:'2026-09-12T09:30:00-05:00',appointmentStatus:'confirmed'}
function fixture(transform?:(path:string,result:Record<string,unknown>)=>Record<string,unknown>){const calls:URL[]=[];const fetcher:typeof fetch=async(input,options)=>{const url=new URL(String(input));calls.push(url);assert.equal(url.origin,'https://services.leadconnectorhq.com');assert.equal(options?.redirect,'error');let value:Record<string,unknown>=url.pathname.startsWith('/locations/')?{location:{id:credentials.locationId,timezone:'America/Chicago'}}:url.pathname==='/calendars/'?{calendars:[{id:cal,name:'Consultations',locationId:credentials.locationId}]}:{events:[event]};if(transform)value=transform(url.pathname,value);return Response.json(value)};return{calls,fetcher}}
test('calendar uses one bounded date window, location timezone, three reads and minimal event fields',async()=>{const f=fixture((_p,v)=>({...v,privateToken:'do not expose'}));const s=await fetchGhlCalendar(credentials,'2026-09',null,f.fetcher);assert.equal(s.events.length,1);assert.equal(s.events[0].start,'2026-09-12T14:00:00.000Z');assert.equal(s.calendarId,cal);assert.equal(f.calls.length,3);assert.ok(Number(f.calls[2].searchParams.get('endTime'))-Number(f.calls[2].searchParams.get('startTime'))<43*86400000);assert.equal(JSON.stringify(s).includes('privateToken'),false)})
test('multiple calendars require a choice and never fan out through every calendar',async()=>{const f=fixture((p,v)=>p==='/calendars/'?{calendars:[{id:cal,name:'One'},{id:'calendar223456789',name:'Two'}]}:v);const s=await fetchGhlCalendar(credentials,'2026-09',null,f.fetcher);assert.equal(s.calendarId,null);assert.equal(f.calls.length,2)})
test('wrong location and unlisted calendar fail before event retrieval',async()=>{for(const kind of ['identity','calendar']){const f=fixture((p,v)=>kind==='identity'&&p.startsWith('/locations/')?{location:{id:'other',timezone:'UTC'}}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',kind==='calendar'?'calendarOTHER123':null,f.fetcher));assert.equal(f.calls.length,2)}})
test('deduplicates records, excludes cancelled/out-of-window events and rejects malformed or cross-calendar events',async()=>{const f=fixture((p,v)=>p==='/calendars/events'?{events:[event,event,{...event,id:'event2234567890',appointmentStatus:'cancelled'},{...event,id:'event3234567890',startTime:'2025-01-01T00:00:00Z',endTime:'2025-01-01T01:00:00Z'}]}:v);assert.equal((await fetchGhlCalendar(credentials,'2026-09',cal,f.fetcher)).events.length,1);for(const change of [{calendarId:'other'},{startTime:'not a date'},{startTime:'2026-09-12T09:00:00'}]){const bad=fixture((p,v)=>p==='/calendars/events'?{events:[{...event,...change}]}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',cal,bad.fetcher))}})
test('calendar permission and large provider responses are explicit failures',async()=>{await assert.rejects(fetchGhlCalendar(credentials,'2026-09',cal,async()=>new Response('secret',{status:401})),/permissions/);const f=fixture((p,v)=>p==='/calendars/events'?{events:Array(1001).fill(event)}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',cal,f.fetcher),/response/)})
test('calendar dates cover leap years, year changes, and Chicago daylight saving',()=>{assert.equal(shiftMonth('2026-12',1),'2027-01');assert.equal(shiftMonth('2026-01',-1),'2025-12');assert.equal(monthDays('2028-02').includes('2028-02-29'),true);const march=monthWindow('2026-03','America/Chicago');assert.equal(new Date(march.start).toISOString(),'2026-03-01T06:00:00.000Z');assert.equal(new Date(march.end).toISOString(),'2026-04-12T05:00:00.000Z');assert.equal(dateKey('2026-09-13T01:00:00Z','America/Chicago'),'2026-09-12')})
const request=(body:unknown)=>new Request('https://portal.example/calendar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})
test('calendar snapshot GET never contacts GHL and never projects credentials',async()=>{const r=await handlePortalGhlCalendar(new Request('https://portal.example/calendar'),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{assert.equal(p.p_action,'read');return {data:{snapshot:null,privateToken:'secret'},error:null}},fetchCalendar:async()=>{throw Error('must not call')}});assert.deepEqual(await r.json(),{revision:null,snapshot:null,refreshedAt:null,error:null,busy:false});assert.equal(r.headers.get('cache-control'),'private, no-store')})
test('calendar authorization and request validation run before provider or write RPC',async()=>{for(const access of [null,{workspace:{id:'w'}}]){const r=await handlePortalGhlCalendar(request({month:'all-history'}),'token',{resolve:async()=>access,rpc:()=>{throw Error('must not call')}});assert.equal(r.status,access?400:404)}})
test('refresh is leased and failures release only its own operation',async()=>{const actions:string[]=[];const r=await handlePortalGhlCalendar(request({month:'2026-09',calendarId:cal}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{actions.push(String(p.p_action));assert.equal(p.p_workspace_id,'w');return {data:p.p_action==='begin'?credentials:{},error:null}},fetchCalendar:async()=>{assert.deepEqual(actions,['begin']);throw Error('private provider payload')}});assert.deepEqual(actions,['begin','fail']);assert.equal(r.status,503);assert.equal(JSON.stringify(await r.json()).includes('private provider'),false)})
