import assert from "node:assert/strict"
import test from "node:test"
import {readFileSync} from "node:fs"
import {createRequire} from "node:module"
import ts from "typescript"
const require=createRequire(import.meta.url),loaded=new Map<string,unknown>()
function load(name:string):Record<string,unknown>{if(loaded.has(name))return loaded.get(name) as Record<string,unknown>;const compiled={exports:{}};const code=ts.transpileModule(readFileSync(`lib/client-portal/${name}.ts`,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function("require","module","exports",code)((p:string)=>p.startsWith("./ghl-")?load(p.slice(2)):require(p),compiled,compiled.exports);loaded.set(name,compiled.exports);return compiled.exports}
const {fetchGhlCalendar}=load('ghl-calendar-provider') as typeof import('../lib/client-portal/ghl-calendar-provider')
const {monthWindow,dateKey,monthDays,shiftMonth}=load('ghl-calendar') as typeof import('../lib/client-portal/ghl-calendar')
const {handlePortalGhlCalendar}=load('ghl-calendar-handler') as typeof import('../lib/client-portal/ghl-calendar-handler')
const credentials={locationId:'location123456789',privateToken:'private-token-synthetic'}
const ownerId='owner1234567890',companyId='company123456789',event={id:'event1234567890',calendarId:'calendar123456789',assignedUserId:ownerId,locationId:credentials.locationId,title:'Consultation',startTime:'2026-09-12T09:00:00-05:00',endTime:'2026-09-12T09:30:00-05:00',appointmentStatus:'confirmed'}
const owner={id:ownerId,name:'Client Owner',isAgencyOwner:true,roles:{locationIds:[credentials.locationId]}}
const binding={companyId,timezone:'America/Chicago',owner:{id:ownerId,name:'Client Owner'}}
function fixture(transform?:(path:string,result:Record<string,unknown>)=>Record<string,unknown>){const calls:URL[]=[];const fetcher:typeof fetch=async(input,options)=>{const url=new URL(String(input));calls.push(url);assert.equal(url.origin,'https://services.leadconnectorhq.com');assert.equal(options?.redirect,'error');let value:Record<string,unknown>=url.pathname.startsWith('/locations/')?{location:{id:credentials.locationId,companyId,timezone:'America/Chicago'}}:url.pathname==='/users/search'?{users:[owner],count:1}:url.pathname==='/calendars/blocked-slots'?{events:[]}:{events:[event]};if(transform)value=transform(url.pathname,value);return Response.json(value)};return{calls,fetcher}}
test('resolves the explicit owner and queries their schedule across booking calendars',async()=>{const f=fixture((_p,v)=>({...v,privateToken:'do not expose'}));const s=await fetchGhlCalendar(credentials,'2026-09',null,f.fetcher);assert.equal(s.events.length,1);assert.equal(s.events[0].start,'2026-09-12T14:00:00.000Z');assert.equal(s.owner.id,ownerId);assert.equal(s.source,'owner-user');assert.equal(f.calls.length,4);for(const call of f.calls.filter(u=>u.pathname.startsWith('/calendars/'))){assert.equal(call.searchParams.get('userId'),ownerId);assert.equal(call.searchParams.has('calendarId'),false)}assert.equal(JSON.stringify(s).includes('privateToken'),false)})
test('bound owner refresh verifies ownership alongside schedule reads with three requests',async()=>{const f=fixture();await fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher);assert.equal(f.calls.length,3);assert.equal(f.calls[0].pathname,'/users/search');assert.equal(f.calls[0].searchParams.get('ids'),ownerId);assert.equal(f.calls.some(u=>u.pathname.startsWith('/locations/')),false)})
test('never guesses an owner from names, admins, business email, or ambiguous matches',async()=>{for(const users of [[{...owner,isAgencyOwner:false}],[owner,{...owner,id:'otherowner123456'}],[{...owner,deleted:true}],[{...owner,roles:{locationIds:['otherlocation123']}}]]){const f=fixture((p,v)=>p==='/users/search'?{users,count:users.length}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',null,f.fetcher),/owner_unavailable/);assert.equal(f.calls.length,2)}})
test('revoked ownership or incomplete user search never publishes a schedule',async()=>{for(const change of [{users:[{...owner,isAgencyOwner:false}],count:1},{users:[owner],count:101}]){const f=fixture((p,v)=>p==='/users/search'?change:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher),/owner_unavailable/)}})
test('wrong locations and cross-user events fail without leaking data',async()=>{for(const change of [{locationId:'otherlocation123'},{assignedUserId:'otherowner123456'}]){const f=fixture((p,v)=>p==='/calendars/events'?{events:[{...event,...change}]}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher),/location/)}})
test('deduplicates records, keeps cancelled appointments, hides private busy titles and excludes deleted records',async()=>{const f=fixture((p,v)=>p==='/calendars/events'?{events:[event,event,{...event,id:'cancelled123456',appointmentStatus:'cancelled'},{...event,id:'deleted1234567',deleted:true}]}:p==='/calendars/blocked-slots'?{events:[{...event,id:'privatebusy123456',title:'Private personal event',notes:'Private notes',startTime:'2026-09-29T00:00:00-05:00',endTime:'2026-09-30T00:00:00-05:00'}]}:v);const s=await fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher);assert.equal(s.events.length,3);assert.equal(s.events.find(e=>e.kind==='busy')?.title,'Busy');assert.equal(s.events.find(e=>e.kind==='busy')?.allDay,true);assert.equal(s.events.some(e=>e.status==='cancelled'),true);assert.equal(JSON.stringify(s).includes('Private'),false)})
test('missing date offsets, permission failures and oversized windows fail explicitly',async()=>{await assert.rejects(fetchGhlCalendar(credentials,'2026-09',null,async()=>new Response('secret',{status:401})),/permissions/);for(const events of [[{...event,startTime:'2026-09-12T09:00:00'}],Array(1001).fill(event)]){const f=fixture((p,v)=>p==='/calendars/events'?{events}:v);await assert.rejects(fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher),/response/)}})
test('calendar dates cover leap years, year changes, and Chicago daylight saving',()=>{assert.equal(shiftMonth('2026-12',1),'2027-01');assert.equal(shiftMonth('2026-01',-1),'2025-12');assert.equal(monthDays('2028-02').includes('2028-02-29'),true);const march=monthWindow('2026-03','America/Chicago');assert.equal(new Date(march.start).toISOString(),'2026-03-01T06:00:00.000Z');assert.equal(new Date(march.end).toISOString(),'2026-04-12T05:00:00.000Z');assert.equal(dateKey('2026-09-13T01:00:00Z','America/Chicago'),'2026-09-12')})
const request=(body:unknown)=>new Request('https://portal.example/calendar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})
test('calendar snapshot GET never contacts GHL and never projects credentials',async()=>{const r=await handlePortalGhlCalendar(new Request('https://portal.example/calendar'),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{assert.equal(p.p_action,'read');return {data:{snapshot:null,privateToken:'secret'},error:null}},fetchCalendar:async()=>{throw Error('must not call')}});assert.deepEqual(await r.json(),{revision:null,snapshot:null,refreshedAt:null,error:null,busy:false});assert.equal(r.headers.get('cache-control'),'private, no-store')})
test('calendar authorization and request validation run before provider or write RPC',async()=>{for(const access of [null,{workspace:{id:'w'}}]){const r=await handlePortalGhlCalendar(request({month:'all-history'}),'token',{resolve:async()=>access,rpc:()=>{throw Error('must not call')}});assert.equal(r.status,access?400:404)}})
test('refresh is leased and failures release only its own operation',async()=>{const actions:string[]=[];const r=await handlePortalGhlCalendar(request({month:'2026-09'}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{actions.push(String(p.p_action));assert.equal(p.p_workspace_id,'w');return {data:p.p_action==='begin'?credentials:{},error:null}},fetchCalendar:async()=>{assert.deepEqual(actions,['begin']);throw Error('private provider payload')}});assert.deepEqual(actions,['begin','fail']);assert.equal(r.status,503);assert.equal(JSON.stringify(await r.json()).includes('private provider'),false)})

test('the browser cannot select a different user or booking calendar',async()=>{for(const field of ['calendarId','userId','owner']){const r=await handlePortalGhlCalendar(request({month:'2026-09',[field]:'someone-else'}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:()=>{throw Error('must not call')}});assert.equal(r.status,400)}})
test('legacy selected-calendar snapshots are hidden during rollout',async()=>{const r=await handlePortalGhlCalendar(new Request('https://portal.example/calendar'),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async()=>({data:{snapshot:{calendarId:'legacy',events:[event]}},error:null})});assert.equal((await r.json()).snapshot,null)})
test('multi-day busy time appears on each covered date, excluding its end midnight',()=>{const {groupCalendarEvents}=load('ghl-calendar') as typeof import('../lib/client-portal/ghl-calendar');const result=groupCalendarEvents([{id:'test',kind:'busy',title:'Busy',start:'2026-09-10T00:00:00-05:00',end:'2026-09-12T00:00:00-05:00',allDay:true,status:'busy'}],'America/Chicago',monthDays('2026-09'));assert.equal(result.get('2026-09-10')?.length,1);assert.equal(result.get('2026-09-11')?.length,1);assert.equal(result.has('2026-09-12'),false)})

const {fetchGhlCalendarNames}=load('ghl-calendar-names-provider') as typeof import('../lib/client-portal/ghl-calendar-names-provider')
const {handlePortalGhlCalendarNames}=load('ghl-calendar-names-handler') as typeof import('../lib/client-portal/ghl-calendar-names-handler')
const {projectCalendar}=load('ghl-calendar-handler') as typeof import('../lib/client-portal/ghl-calendar-handler')
const contactId='contact123456789',otherContact='contact987654321'
const titleSnapshot=async()=>{const f=fixture((p,v)=>p==='/calendars/events'?{events:[{...event,contactId}]}:v);return fetchGhlCalendar(credentials,'2026-09',binding,f.fetcher)}
const contact={id:contactId,locationId:credentials.locationId,firstName:'Manuel',lastName:'Rodriguez',city:'Fort Worth',opportunities:[{name:'Unverified garage project'}],customFields:[{id:'budget',value:'120000'}],email:'not-for-the-calendar@example.invalid'}
test('calendar refresh records exact contact links privately without adding contact requests',async()=>{const s=await titleSnapshot();assert.equal(s.eventContacts?.[event.id],contactId);assert.equal(s.namesStatus,'pending');assert.equal(s.contactLabels,undefined)})
test('titles use exact contact IDs and contact facts, never a lone opportunity or custom field',async()=>{const s=await titleSnapshot();let calls=0;const labels=await fetchGhlCalendarNames(credentials,s,async(input,options)=>{calls++;assert.equal(String(input),'https://services.leadconnectorhq.com/contacts/search');const body=JSON.parse(String(options?.body));assert.deepEqual(body.filters,[{group:'OR',filters:[{field:'id',operator:'eq',value:contactId}]}]);assert.equal(body.locationId,credentials.locationId);assert.equal(body.pageLimit,1);return Response.json({contacts:[contact],total:1})});assert.equal(calls,1);assert.deepEqual(labels,{[contactId]:{name:'Manuel Rodriguez',city:'Fort Worth'}});const view=projectCalendar({snapshot:{...s,contactLabels:labels}});assert.equal(view.snapshot?.events[0].title,'Manuel Rodriguez · Fort Worth');assert.equal(view.snapshot?.events[0].originalTitle,event.title);assert.equal(view.snapshot?.events[0].contactCity,'Fort Worth');const serialized=JSON.stringify(view);for(const forbidden of [contactId,'garage','120000','example.invalid','eventContacts','companyId'])assert.equal(serialized.includes(forbidden),false)})
test('missing, deleted or unnamed contacts retain the original appointment title',async()=>{const s=await titleSnapshot();for(const contacts of [[],[{...contact,deleted:true}],[{...contact,firstName:'',lastName:'',contactName:''}]]){const labels=await fetchGhlCalendarNames(credentials,s,async()=>Response.json({contacts,total:contacts.length}));assert.equal(projectCalendar({snapshot:{...s,contactLabels:labels}}).snapshot?.events[0].title,event.title)}})
test('wrong-account, wrong-ID, duplicate and truncated contact responses are rejected',async()=>{const s=await titleSnapshot();for(const response of [{contacts:[{...contact,id:otherContact}],total:1},{contacts:[{...contact,locationId:'otherlocation123'}],total:1},{contacts:[contact,contact],total:2},{contacts:[contact],total:2}])await assert.rejects(fetchGhlCalendarNames(credentials,s,async()=>Response.json(response)),/location|response/)})
test('contact lookup does not run for Busy blocks, invalid links or unlinked appointments',async()=>{const s=await titleSnapshot();s.events[0].kind='busy';await fetchGhlCalendarNames(credentials,s,async()=>{throw Error('must not call')});s.events[0].kind='appointment';s.eventContacts={[event.id]:'invalid'};await fetchGhlCalendarNames(credentials,s,async()=>{throw Error('must not call')});delete s.eventContacts;await fetchGhlCalendarNames(credentials,s,async()=>{throw Error('must not call')})})
test('title lookup batches growing calendars with at most two requests in flight',async()=>{const s=await titleSnapshot();s.events=Array.from({length:251},(_,i)=>({...s.events[0],id:`event${i}`}));s.eventContacts=Object.fromEntries(s.events.map((e,i)=>[e.id,`contact${String(i).padStart(12,'0')}`]));let calls=0,active=0,peak=0;const labels=await fetchGhlCalendarNames(credentials,s,async(_i,o)=>{calls++;active++;peak=Math.max(peak,active);const b=JSON.parse(String(o?.body));assert.ok(b.pageLimit<=100);await new Promise(r=>setTimeout(r,5));active--;return Response.json({total:b.pageLimit,contacts:b.filters[0].filters.map((f:{value:string})=>({...contact,id:f.value}))})});assert.equal(calls,3);assert.equal(peak,2);assert.equal(Object.keys(labels).length,251)})
test('title lookup fails safely for permissions and oversized provider responses',async()=>{const s=await titleSnapshot();await assert.rejects(fetchGhlCalendarNames(credentials,s,async()=>new Response('secret',{status:403})),/permissions/);await assert.rejects(fetchGhlCalendarNames(credentials,s,async()=>new Response(' '.repeat(524289))),/response/)})
test('title endpoint rejects injected IDs before acquiring a lease',async()=>{for(const body of [{snapshotId:'00000000-0000-4000-8000-000000000009',contactId},{snapshotId:'not-a-uuid'},{}]){const r=await handlePortalGhlCalendarNames(request(body),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:()=>{throw Error('must not call')}});assert.equal(r.status,400)}})
test('title enrichment uses only the leased snapshot and sanitizes its response',async()=>{const snapshot=await titleSnapshot(),actions:string[]=[];const r=await handlePortalGhlCalendarNames(request({snapshotId:'00000000-0000-4000-8000-000000000009'}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{actions.push(String(p.p_action));assert.equal(p.p_workspace_id,'w');return {data:p.p_action==='begin'?{...credentials,snapshot}:{snapshot:{...snapshot,contactLabels:p.p_labels},privateToken:'secret'},error:null}},fetchNames:async(_c,s)=>{assert.equal(s,snapshot);return {[contactId]:{name:'Manuel Rodriguez'}}}});assert.deepEqual(actions,['begin','finish']);const view=await r.json();assert.equal(view.snapshot.events[0].title,'Manuel Rodriguez');assert.equal(JSON.stringify(view).includes('secret'),false)})
test('title errors release their own lease without changing schedule data',async()=>{const actions:string[]=[];const r=await handlePortalGhlCalendarNames(request({snapshotId:'00000000-0000-4000-8000-000000000009'}),'token',{resolve:async()=>({workspace:{id:'w'}}),rpc:async(p)=>{actions.push(String(p.p_action));return {data:p.p_action==='begin'?{...credentials,snapshot:await titleSnapshot()}:{},error:null}},fetchNames:async()=>{throw Error('private provider error')}});assert.deepEqual(actions,['begin','fail']);assert.equal(r.status,503);assert.equal(JSON.stringify(await r.json()).includes('private provider'),false)})
