import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const migration = readFileSync("supabase/migrations/20260822090000_client_portal_foundation.sql", "utf8")
const testDeliveryFix = readFileSync("supabase/migrations/20260822110000_deliver_test_client_portal_links.sql", "utf8")
const messageProjectionMigration = readFileSync("supabase/migrations/20260828090000_client_portal_message_projection.sql", "utf8")
const portalChatMigration = readFileSync("supabase/migrations/20260828140000_client_portal_chat.sql", "utf8")
const portalInteractionsMigration = readFileSync("supabase/migrations/20260828170000_client_portal_message_interactions.sql", "utf8")
const portalAttachmentKeyFixMigration = readFileSync("supabase/migrations/20260829090000_fix_client_portal_attachment_keys.sql", "utf8")
const proxy = readFileSync("proxy.ts", "utf8")
const portalPage = readFileSync("app/client-portal/session/[token]/page.tsx", "utf8")
const portalShell = readFileSync("components/client-portal/ClientPortalShell.tsx", "utf8")
const portalChat = readFileSync("components/client-portal/ClientPortalChat.tsx", "utf8")
const portalComposerViewport = readFileSync("components/client-portal/client-portal-composer-viewport.ts", "utf8")
const composerKeyboardSlide = readFileSync("components/communications/composer-keyboard-slide.ts", "utf8")
const portalMessages = readFileSync("lib/client-portal/messages.ts", "utf8")
const portalMessagesRoute = readFileSync("app/api/client-portal/session/[token]/messages/route.ts", "utf8")
const portalReactionsRoute = readFileSync("app/api/client-portal/session/[token]/reactions/route.ts", "utf8")
const staffReactionsRoute = readFileSync("app/api/workspaces/[workspaceSlug]/communications/reactions/route.ts", "utf8")
const portalAttachmentRoute = readFileSync("app/api/client-portal/session/[token]/messages/[messageId]/attachment/route.ts", "utf8")
const portalSession = readFileSync("lib/client-portal/session.ts", "utf8")
const portalDomain = readFileSync("lib/client-portal/domain.ts", "utf8")
const onboardingRuntime = readFileSync("lib/onboarding/canonical.ts", "utf8")
const onboardingActions = readFileSync("app/onboarding/session/[token]/actions.ts", "utf8")
const onboardingForm = readFileSync("components/onboarding/OnboardingForm.tsx", "utf8")
const outbox = readFileSync("lib/onboarding/outbox.ts", "utf8")
const settings = readFileSync("app/[workspaceSlug]/settings/page.tsx", "utf8")
const settingsActions = readFileSync("app/[workspaceSlug]/settings/actions.ts", "utf8")

test("client portal sessions are durable relationship credentials provisioned by onboarding completion", () => {
    assert.match(migration, /create table if not exists public\.client_portal_sessions/u)
    assert.match(migration, /unique \(workspace_id, relationship_id\)/u)
    assert.match(migration, /session_token ~ '\^\[a-f0-9\]\{64\}\$'/u)
    assert.match(migration, /after update of status on public\.relationship_onboarding_sessions/u)
    assert.match(migration, /new\.status = 'completed'/u)
    assert.match(migration, /on conflict \(workspace_id, relationship_id\) do update/u)
    assert.match(testDeliveryFix, /create or replace function public\.provision_client_portal_after_onboarding/u)
    assert.doesNotMatch(testDeliveryFix, /new\.is_test/u)
})

test("completion queues one idempotent portal link through the existing omnichannel outbox", () => {
    assert.match(migration, /'client_portal_link'/u)
    assert.match(migration, /'client-portal-link:' \|\| new\.id::text/u)
    assert.match(migration, /portal_session_id/u)
    assert.match(outbox, /row\.kind === "client_portal_link"/u)
    assert.match(outbox, /getClientPortalUrl/u)
    assert.match(outbox, /sendCommunicationDeliveries/u)
    assert.match(outbox, /Client portal link/u)
})

test("portal custom domains have independent settings, verification, and routing", () => {
    assert.match(migration, /custom_client_portal_domain_status/u)
    assert.match(migration, /resolve_workspace_public_domain/u)
    assert.match(migration, /'client_portal'::text/u)
    assert.match(proxy, /resolve_workspace_public_domain/u)
    assert.match(proxy, /x-betelgeze-custom-client-portal-domain/u)
    assert.match(proxy, /`\/client-portal\/session\/\$\{customToken\[1\]\}`/u)
    assert.match(portalDomain, /customDomainVerified/u)
    assert.match(settings, /surface="client_portal"/u)
    assert.match(settings, /id="client-portal-domain"/u)
})

test("client portal settings expose the onboarding-equivalent domain process to owners and admins", () => {
    const portalSection = settings.indexOf('id="client-portal"')
    const portalDomain = settings.indexOf('id="client-portal-domain"')
    const connectionsSection = settings.indexOf('id="connections"')
    assert.ok(portalSection >= 0 && portalDomain > portalSection && connectionsSection > portalDomain)
    assert.match(settings, /surface="client_portal"[\s\S]*canManage=\{role === "owner" \|\| role === "admin"\}/u)
    assert.match(settingsActions, /saveWorkspaceClientPortalDomain[\s\S]*requireWorkspace\(slug, "admin"\)/u)
    assert.match(settingsActions, /verifyWorkspaceClientPortalDomain[\s\S]*requireWorkspace\(slug, "admin"\)/u)
    assert.match(settingsActions, /cancelWorkspaceClientPortalDomain[\s\S]*requireWorkspace\(slug, "admin"\)/u)
})

test("completed onboarding redirects to a branded portal with a safe invalid-link probe", () => {
    assert.match(onboardingRuntime, /getClientPortalUrlForOnboardingSession/u)
    assert.match(onboardingActions, /redirect\(outcome\.clientPortalUrl\)/u)
    assert.match(onboardingForm, /window\.location\.assign\(outcome\.clientPortalUrl\)/u)
    assert.match(portalSession, /loadPublishedOnboardingConfiguration/u)
    assert.match(portalSession, /\.neq\("status", "archived"\)/u)
    assert.doesNotMatch(portalSession, /\.is\("archived_at"/u)
    assert.match(portalPage, /<OnboardingThemeProvider theme=\{theme\}>/u)
    assert.match(portalPage, /<ClientPortalShell/u)
    assert.match(portalPage, /data-betelgeze-client-portal-session="invalid"/u)
    assert.match(portalShell, /var\(--onboarding-primary/u)
    assert.match(portalShell, /Good morning/u)
    assert.match(portalShell, /Good afternoon/u)
    assert.match(portalShell, /Good evening/u)
    assert.match(portalShell, />Required actions</u)
    assert.match(portalShell, />Your results</u)
    assert.match(portalShell, />Resource submission</u)
    assert.match(portalShell, /md:w-\[30rem\]/u)
    assert.match(portalShell, /aria-label=\{`Back from/u)
})

test("the portal message bridge is token scoped and strips staff-only communication data", () => {
    assert.match(messageProjectionMigration, /create or replace function public\.client_portal_messages/u)
    assert.match(messageProjectionMigration, /auth\.role\(\) = 'service_role'/u)
    assert.match(messageProjectionMigration, /message\.workspace_id = p_workspace_id/u)
    assert.match(messageProjectionMigration, /message\.relationship_id = p_relationship_id/u)
    assert.match(messageProjectionMigration, /revoke all on function public\.client_portal_messages[\s\S]*from public, anon, authenticated/u)
    assert.match(messageProjectionMigration, /grant execute on function public\.client_portal_messages[\s\S]*to service_role/u)
    assert.doesNotMatch(messageProjectionMigration, /provider_message_id/u)
    assert.doesNotMatch(messageProjectionMigration, /sender_user_id/u)
    assert.doesNotMatch(messageProjectionMigration, /message\.error/u)
    assert.match(portalInteractionsMigration, /create or replace function public\.client_portal_messages_v2/u)
    assert.match(portalInteractionsMigration, /auth\.role\(\) = 'service_role'/u)
    assert.match(portalInteractionsMigration, /message\.workspace_id = p_workspace_id/u)
    assert.match(portalInteractionsMigration, /message\.relationship_id = p_relationship_id/u)
    assert.doesNotMatch(portalInteractionsMigration, /provider_message_id/u)
    assert.doesNotMatch(portalInteractionsMigration, /reactor_user_id/u)
    assert.doesNotMatch(portalInteractionsMigration, /reactor_address/u)
    assert.match(portalMessages, /supabaseAdmin\.rpc\("client_portal_messages_v2"/u)
    assert.match(portalMessagesRoute, /resolveClientPortalAccessByToken\(token\)/u)
    assert.doesNotMatch(portalMessagesRoute, /loadPublishedOnboardingConfiguration/u)
    assert.match(portalMessagesRoute, /Cache-Control/u)
    assert.match(portalMessagesRoute, /private, no-store/u)
    assert.doesNotMatch(portalMessagesRoute, /storagePath: message\.attachment\.storagePath/u)
    assert.match(portalMessagesRoute, /export async function POST/u)
    assert.match(portalMessagesRoute, /provider: "client_portal"/u)
    assert.match(portalMessagesRoute, /direction: "inbound"/u)
    assert.match(portalMessagesRoute, /sender_kind: "client"/u)
    assert.match(portalMessagesRoute, /notifyClientChatMessage/u)
    assert.match(portalMessagesRoute, /client_request_id: clientRequestId/u)
    assert.match(portalMessagesRoute, /reply_to_message_id: replyToMessageId/u)
    assert.match(portalMessagesRoute, /export async function DELETE/u)
    assert.match(portalMessagesRoute, /target\.data\.provider !== "client_portal"/u)
    assert.match(portalMessagesRoute, /delete_client_portal_message/u)
})

test("the client portal mirrors the approved BE message interactions without making provider messages mutable", () => {
    assert.match(portalPage, /token=\{token\}/u)
    assert.match(portalShell, /<ClientPortalChat token=\{token\}/u)
    assert.match(portalChat, /fetch\(`\$\{apiPath\}\?limit=100`/u)
    assert.match(portalChat, /method: "POST"/u)
    assert.match(portalChat, /MessageMediaLightbox/u)
    assert.match(portalChat, /Load earlier messages/u)
    assert.match(portalChat, /Enter to send/u)
    assert.match(portalChat, /PrimaryMessageActions/u)
    assert.match(portalChat, /MessageReactionActions/u)
    assert.match(portalChat, /message\.source === "portal"/u)
    assert.match(portalChat, /message\.source === "whatsapp"/u)
    assert.match(portalChat, /bg-\[#154D37\]/u)
    assert.match(portalChat, /replyToMessageId: optimistic\.replyToMessageId/u)
    assert.match(portalChat, /start\.maxDeltaX > 52/u)
    assert.match(portalChat, /start\.minDeltaX < -52/u)
    assert.match(portalChat, /mergeLatestSnapshot/u)
    assert.doesNotMatch(portalChat, /useComposerKeyboardSlide|composerFooterRef/u)
    assert.match(portalChat, /<ChatComposerInput/u)
    assert.match(portalChat, /useClientPortalComposerViewport\(textareaRef\)/u)
    assert.match(portalShell, /data-client-portal-panel/u)
    assert.match(portalShell, /h-\[var\(--client-portal-viewport-bottom,100dvh\)\]/u)
    assert.match(portalChat, /observeMessagePaneResize\(scrollRef\.current, \(\) => followingLatestRef\.current, true\)/u)
    assert.match(portalChat, /mx-auto flex min-h-full max-w-2xl flex-col/u)
    assert.match(portalChat, /aria-hidden="true" className="mt-auto"/u)
    assert.match(portalChat, /focus\(\{ preventScroll: true \}\)/u)
    assert.doesNotMatch(portalChat, /event\.pointerType !== "touch"|setSelectionRange/u)
    assert.match(portalChat, /style=\{\{ overflowAnchor: "none" \}\}/u)
    assert.match(portalChat, /touch-pan-y overflow-x-hidden overflow-y-auto overscroll-x-none overscroll-y-contain/u)
    assert.match(portalChat, /flex touch-manipulation items-center/u)
    assert.match(portalComposerViewport, /PORTAL_KEYBOARD_MOTION_MS = 300/u)
    assert.match(portalComposerViewport, /visualViewport\?\.addEventListener\("resize", holdPortalViewport\)/u)
    assert.match(portalComposerViewport, /visualViewport\?\.addEventListener\("scroll", holdPortalViewport\)/u)
    assert.match(portalComposerViewport, /document\.addEventListener\("visibilitychange", handleVisibility\)/u)
    assert.match(portalComposerViewport, /window\.addEventListener\("pagehide", suspendPortalViewport\)/u)
    assert.match(portalComposerViewport, /composer\.blur\(\)/u)
    assert.match(portalComposerViewport, /requestChatViewportMotion\(panel, appliedViewportBottom, viewportBottom/u)
    assert.match(portalComposerViewport, /const nextBottom = Math\.min\(keyboardViewportBottom \?\? viewportBottom, viewportBottom\)/u)
    assert.match(portalComposerViewport, /writeViewportBottom\(keyboardViewportBottom\)/u)
    assert.match(composerKeyboardSlide, /KEYBOARD_SLIDE_DURATION_MS = 220/u)
    assert.match(portalReactionsRoute, /message\.data\.direction !== "outbound"/u)
    assert.match(portalReactionsRoute, /direction: "inbound"/u)
    assert.match(staffReactionsRoute, /message\.provider === "client_portal"/u)
    assert.match(staffReactionsRoute, /if \(!portalNative\)/u)
    const communicationsWorkspace = readFileSync("components/communications/CommunicationsWorkspace.tsx", "utf8")
    const communicationInteractions = readFileSync("lib/communications/interactions.ts", "utf8")
    assert.match(communicationInteractions, /message\.provider === "client_portal"/u)
    assert.match(communicationsWorkspace, /const canInteract = clientMessageSupportsReaction\(message, reactionCutoff\)/u)
    assert.match(communicationsWorkspace, /payload\.eventType === "DELETE"[\s\S]*updates\.removeMessage\(messageId\)/u)
    assert.match(communicationsWorkspace, /updates\.applySnapshot\(read, result\)/u)
})

test("portal attachment access stays relationship scoped without exposing storage paths", () => {
    assert.match(portalChatMigration, /create or replace function public\.client_portal_message_attachment_access/u)
    assert.match(portalChatMigration, /auth\.role\(\) = 'service_role'/u)
    assert.match(portalChatMigration, /message\.workspace_id = p_workspace_id/u)
    assert.match(portalChatMigration, /message\.relationship_id = p_relationship_id/u)
    assert.match(portalChatMigration, /encrypted_file\.scope_id = p_relationship_id/u)
    assert.match(portalChatMigration, /relationships\/' \|\| p_relationship_id::text \|\| '\/client-messages/u)
    assert.match(portalChatMigration, /revoke all on function public\.client_portal_message_attachment_access[\s\S]*from public, anon, authenticated/u)
    assert.match(portalAttachmentRoute, /resolveClientPortalAccessByToken\(token\)/u)
    assert.match(portalAttachmentRoute, /loadClientPortalAttachmentAccess/u)
    assert.match(portalAttachmentRoute, /X-Content-Type-Options/u)
    assert.doesNotMatch(portalMessagesRoute, /storagePath/u)
    assert.match(portalAttachmentKeyFixMigration, /content_secret\.decrypted_secret/u)
    assert.match(portalAttachmentKeyFixMigration, /file_secret\.decrypted_secret/u)
    assert.doesNotMatch(portalAttachmentKeyFixMigration, /content_secret\.secret/u)
    assert.doesNotMatch(portalAttachmentKeyFixMigration, /file_secret\.secret/u)
    assert.match(portalAttachmentKeyFixMigration, /encrypted_file\.scope_id = p_relationship_id/u)
})

test("client portal stickers use the shared bubbleless visual contract", () => {
    assert.match(portalChat, /const isSticker = message\.attachment\?\.kind === "sticker"/u)
    assert.match(portalChat, /isSticker \? "relative max-w-52 bg-transparent p-0 pb-1 shadow-none"/u)
    assert.match(portalChat, /h-auto max-h-48 w-auto max-w-52 object-contain drop-shadow-lg/u)
    assert.match(portalChat, /!isSticker && message\.reactions\.length/u)
})
