import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"

const integrations = readFileSync("lib/workspace-integrations.ts", "utf8")
const migration = readFileSync("supabase/migrations/20260812110000_universal_workspace_connections.sql", "utf8")
const settingsUi = readFileSync("components/admin/WorkspaceConnections.tsx", "utf8")
const stripeStart = readFileSync("app/api/workspace-connections/stripe/start/route.ts", "utf8")
const stripeCallback = readFileSync("app/api/workspace-connections/stripe/callback/route.ts", "utf8")
const stripeWebhook = readFileSync("app/api/stripe/webhook/route.ts", "utf8")
const whatsapp = readFileSync("lib/client-messages/meta-whatsapp.ts", "utf8")
const whatsappWebhook = readFileSync("app/api/client-messages/meta/whatsapp/route.ts", "utf8")
const saleAutomation = readFileSync("lib/client-sales/automation.ts", "utf8")
const outbox = readFileSync("lib/onboarding/outbox.ts", "utf8")
const twilio = readFileSync("lib/client-messages/twilio.ts", "utf8")
const twilioWebhook = readFileSync("app/api/client-messages/twilio/route.ts", "utf8")
const omnichannelMigration = readFileSync("supabase/migrations/20260817110000_twilio_omnichannel_messaging.sql", "utf8")
const metaAdsMigration = readFileSync("supabase/migrations/20260830110000_meta_ads_workspace_connection.sql", "utf8")
const metaAdsStart = readFileSync("app/api/workspace-connections/meta-ads/start/route.ts", "utf8")
const metaAdsCallback = readFileSync("app/api/workspace-connections/meta-ads/callback/route.ts", "utf8")
const privacy = readFileSync("app/privacy/page.tsx", "utf8")
const terms = readFileSync("app/terms/page.tsx", "utf8")

test("connection candidates activate atomically and keep a one-generation rollback", () => {
    assert.match(migration, /candidate_config_encrypted/u)
    assert.match(migration, /create or replace function public\.activate_workspace_integration_candidate/u)
    assert.match(migration, /previous_mode = mode/u)
    assert.match(migration, /create or replace function public\.restore_workspace_integration_previous/u)
    assert.match(integrations, /stageWorkspaceIntegrationCandidate/u)
    assert.match(integrations, /verifyAndActivateWorkspaceIntegrationCandidate/u)
})

test("OAuth state is short lived, random, hashed, single use, and tied to its initiating user", () => {
    assert.match(integrations, /randomBytes\(32\)\.toString\("base64url"\)/u)
    assert.match(integrations, /createHash\("sha256"\)/u)
    assert.match(integrations, /Date\.now\(\) \+ 10 \* 60_000/u)
    assert.match(integrations, /data\.status !== "pending"/u)
    assert.match(stripeCallback, /authenticated\.user\.id !== attempt\.requested_by/u)
    assert.match(stripeStart, /createConnectionAttempt/u)
    assert.match(metaAdsStart, /createConnectionAttempt/u)
    assert.match(metaAdsCallback, /authenticated\.user\.id !== attempt\.requested_by/u)
})

test("Meta Ads template installation atomically creates its optional workspace connection", () => {
    assert.match(metaAdsMigration, /create or replace function public\.install_onboarding_service_template/u)
    assert.match(metaAdsMigration, /public\.save_onboarding_service_revision/u)
    assert.match(metaAdsMigration, /insert into public\.workspace_integrations/u)
    assert.match(metaAdsMigration, /on conflict \(workspace_id, provider\) do nothing/u)
    assert.doesNotMatch(metaAdsMigration, /select id, 'meta_ads'/u)
})

test("Meta Ads uses server-side OAuth, explicit portfolio selection, and read-only ads access", () => {
    assert.match(metaAdsStart, /business_management,ads_read/u)
    assert.match(metaAdsStart, /META_ADS_LOGIN_CONFIG_ID/u)
    assert.match(metaAdsCallback, /fb_exchange_token/u)
    assert.match(metaAdsCallback, /stageMetaAdsWorkspaceIntegrationCandidate/u)
    assert.match(integrations, /getMetaAdsBusinessOptions/u)
    assert.match(integrations, /selectMetaAdsWorkspaceIntegrationBusiness/u)
    assert.match(integrations, /appsecret_proof/u)
    assert.match(settingsUi, /Choose a Business Portfolio/u)
    assert.doesNotMatch(metaAdsStart, /ads_management/u)
    assert.match(privacy, /Connected Meta Business Portfolios/u)
    assert.match(privacy, /read-only advertising access/u)
    assert.match(privacy, /support@betelgeze\.com/u)
})

test("Settings uses one popup lifecycle with automatic and manual connection paths", () => {
    assert.match(settingsUi, /role="dialog"/u)
    assert.match(settingsUi, /Continue to Stripe/u)
    assert.match(settingsUi, /Continue with Meta/u)
    assert.match(settingsUi, /Enter Twilio credentials/u)
    assert.match(settingsUi, /Use manual credentials/u)
    assert.match(settingsUi, /The current connection remains active until the replacement passes every required check/u)
    assert.match(settingsUi, /Restore previous/u)
    assert.match(settingsUi, /Verify now/u)
})

test("manual Stripe verification derives account mode from the credential instead of a missing Account property", () => {
    assert.match(integrations, /stripeAccountMode/u)
    assert.doesNotMatch(integrations, /mode: account\.livemode \? "live" : "test"/u)
})

test("provider runtime operations use the workspace connection", () => {
    assert.match(whatsapp, /getWorkspaceProviderConfig\(workspaceId, "meta_whatsapp"\)/u)
    assert.match(saleAutomation, /workspaceId: sale\.workspace_id/u)
    assert.match(outbox, /workspaceId: row\.workspace_id/u)
    assert.match(saleAutomation, /getWorkspaceProviderConfig\(sale\.workspace_id, "meta_whatsapp"\)/u)
    assert.match(saleAutomation, /sendCommunicationDeliveries/u)
    assert.match(outbox, /sendCommunicationDeliveries/u)
    assert.match(integrations, /onboarding_template_language: template\.language/u)
})

test("webhooks resolve workspace identity before processing tenant data", () => {
    assert.match(stripeWebhook, /getWorkspaceIdForConnectedAccount\("stripe", externalAccountId\)/u)
    assert.match(stripeWebhook, /recordWorkspaceConnectionWebhook\(workspaceId, "stripe"\)/u)
    assert.match(stripeWebhook, /candidate\.livemode === null \|\| candidate\.livemode === event\.livemode/u)
    assert.match(stripeWebhook, /account\.application\.deauthorized/u)
    assert.match(stripeWebhook, /disconnectWorkspaceIntegration\(workspaceId, "stripe"\)/u)
    assert.match(stripeWebhook, /isResumableAutomationEvent/u)
    assert.match(integrations, /STRIPE_APP_TEST_WEBHOOK_SECRET/u)
    assert.match(integrations, /STRIPE_APP_LIVE_WEBHOOK_SECRET/u)
    assert.match(whatsappWebhook, /getWorkspaceIdForWhatsAppPhoneNumber\(phoneNumberIds\[0\]\)/u)
    assert.match(whatsappWebhook, /handleSaleConsentConfirmation\(\{\s*workspaceId,/u)
    assert.match(twilioWebhook, /getWorkspaceIdForTwilioNumber\(businessNumber\)/u)
    assert.match(twilioWebhook, /validateTwilioSignature/u)
    assert.match(twilioWebhook, /provider: "twilio_sms"/u)
    assert.match(saleAutomation, /findPendingConfirmedSale\(fromAddress, workspaceId, messageId\)/u)
    assert.match(saleAutomation, /\.eq\("workspace_id", workspaceId\)/u)
})

test("Twilio is workspace-owned and messages retain per-provider delivery state", () => {
    assert.match(integrations, /"twilio_sms"/u)
    assert.match(twilio, /getWorkspaceProviderConfig\(input\.workspaceId, "twilio_sms"\)/u)
    assert.match(twilio, /StatusCallback/u)
    assert.match(twilio, /to === from/u)
    assert.match(omnichannelMigration, /communication_message_deliveries/u)
    assert.match(omnichannelMigration, /communication_primary_provider/u)
    assert.match(omnichannelMigration, /communication_delivery_mode/u)
})

test("public privacy policy includes Twilio messaging disclosures", () => {
    assert.match(privacy, /SMS and MMS Communications/u)
    assert.match(privacy, /Message and data rates may apply/u)
    assert.match(privacy, /reply STOP/u)
    assert.match(privacy, /reply HELP/u)
    assert.match(privacy, /do not sell, rent, or share mobile phone numbers, SMS opt-in data, or messaging consent/u)
})

test("public messaging terms include A2P campaign disclosures", () => {
    assert.match(terms, /Betelgeze Client Messaging/u)
    assert.match(terms, /Message frequency varies/u)
    assert.match(terms, /Message and data rates may apply/u)
    assert.match(terms, /reply HELP/u)
    assert.match(terms, /reply STOP/u)
    assert.match(terms, /mailto:support@betelgeze\.com/u)
    assert.match(terms, /Carriers are not liable for any delayed or undelivered messages/u)
    assert.match(terms, /href="\/privacy"/u)
    assert.match(privacy, /href="\/terms"/u)
})

test("legacy Stripe and WhatsApp credentials remain available during cutover", () => {
    assert.match(integrations, /if \(data\.mode === "platform_legacy"\) return legacyConfig\(provider\)/u)
    assert.match(integrations, /META_WHATSAPP_ACCESS_TOKEN/u)
    assert.match(integrations, /STRIPE_SECRET_KEY/u)
    assert.match(migration, /platform_legacy escape hatch/u)
})
