export type ServiceSopStep = {
    key: string
    title: string
    description?: string
}

export type ServiceDefinition = {
    key: string
    title: string
    description: string
    requiredModuleKeys: string[]
    sopSteps: ServiceSopStep[]
}

export const SERVICES: Record<string, ServiceDefinition> = {
    "landing-page-creation": {
        key: "landing-page-creation",
        title: "Landing Page Creation",
        description:
            "Fulfilment work for landing page planning, copy, design, build, QA, and launch preparation.",
        requiredModuleKeys: ["website-lp"],
        sopSteps: [],
    },
    "google-ads": {
        key: "google-ads",
        title: "Google Search Ads",
        description:
            "Fulfilment work for Google Search Ads setup, tracking, launch, and ongoing campaign preparation.",
        requiredModuleKeys: ["google-search-ads"],
        sopSteps: [],
    },
    "full-website-design": {
        key: "full-website-design",
        title: "Full Website Design",
        description:
            "Fulfilment work for full website structure, copy, design, build, QA, and launch preparation.",
        requiredModuleKeys: ["website-lp"],
        sopSteps: [],
    },
    seo: {
        key: "seo",
        title: "SEO",
        description:
            "Fulfilment work for SEO planning, technical review, on-page improvements, and content direction.",
        requiredModuleKeys: [],
        sopSteps: [
            {
                key: "confirm-access-and-pre-sale-groundwork",
                title: "Confirm access and pull pre-sale groundwork",
                description: [
                    "Stage: Setup",
                    "",
                    "Goal: Make sure you can actually work the account and have the existing research before touching anything.",
                    "",
                    "Steps:",
                    "1. Confirm you can log into the client's website admin/CMS and their Google Business Profile (GBP).",
                    "2. Open the relationship assets and context notes. The pre-sale groundwork, including the initial Leadsnap heatmap, should be there. Read it before starting.",
                    "3. Note the client's main service area and primary service from that context.",
                    "",
                    "Done when: Website and GBP access are confirmed, and you have read the existing Strategy and Context.",
                    "",
                    "SOP ref: New Local SEO Client Workflow, page 3.",
                    "",
                    "Escalate if: You do not have website or GBP access, or cannot find the relationship context. Access and credentials are not something to guess at. Ask a manager.",
                ].join("\n"),
            },
            {
                key: "run-benchmark-heatmap",
                title: "Run benchmark heatmap",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Establish a starting-point ranking benchmark and spot obvious gaps.",
                    "",
                    "Tools: Leadsnap (app.leadsnap.com).",
                    "",
                    "Steps:",
                    "1. Run a heatmap on the client's main keyword in Leadsnap.",
                    "2. Save the starting grid as a screenshot to this task. Mostly red is a normal low starting point.",
                    "3. Note the top-10 competitors' review counts and photo counts. If the client is well behind, flag that they need to start gathering reviews and photos.",
                    "4. Scan for obvious black-hat or fake listings, such as all-caps keyword-stuffed names or strange locations. Log any for later.",
                    "",
                    "Done when: Benchmark heatmap is saved, competitor review/photo gap is noted, and suspicious listings are logged.",
                    "",
                    "SOP ref: Benchmarking + Checking For Obvious Flaws, page 3.",
                    "",
                    "Escalate if: You genuinely cannot identify the main keyword. Do subtask 3 first, then ask if still stuck.",
                ].join("\n"),
            },
            {
                key: "easy-win-audit",
                title: "Easy-win audit: website and GBP quick checks",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Run five fast checks that reveal easy ranking wins. Log pass/fail on each; this becomes your fix list.",
                    "",
                    "Steps:",
                    "1. NAP visible and matching: business Name, Address, and Phone are visible on the page and match the GBP exactly.",
                    "2. Title + H1: hover the browser tab to read the page title. Main keyword + city should be in the title tag and H1. Missing = easy win.",
                    "3. Indexed pages: Google site:clientdomain.com, open Tools, and read the indexed count. We want 30+. Under that = flag it.",
                    "4. Schema: paste the site into validator.schema.org. No LocalBusiness schema = easy win.",
                    "5. Embed map: confirm a Google Map is embedded on the homepage.",
                    "",
                    "Done when: All five checks are marked pass/fail with notes.",
                    "",
                    "SOP ref: GBP / Website Checks For Easy Wins, pages 4-5.",
                    "",
                    "Escalate if: Nothing here is judgment-based. These are mechanical checks. Use the SOP screenshots if a step is visually unclear.",
                ].join("\n"),
            },
            {
                key: "pick-main-keyword-and-competitive-analysis",
                title: "Pick the main keyword and run competitive analysis",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Lock the primary keyword and learn the competitive bar. This sets targets for the GBP subtasks.",
                    "",
                    "Tools: GMB Everywhere Chrome extension, GMB Everywhere Category Finder, and Leadsnap volume/competitiveness.",
                    "",
                    "Steps:",
                    "1. Decide the main keyword. Usually obvious, such as plumber Springfield. If unsure, use AI to suggest, then confirm with the client.",
                    "2. Run the keyword through GMB Everywhere Local Scan.",
                    "3. Record the top-20 averages: number of categories, number of services, and profile features. These are your targets later.",
                    "",
                    "Done when: Main keyword is confirmed and competitive benchmarks for categories, services, and features are recorded.",
                    "",
                    "SOP ref: Choose the MAIN Keyword / Competitive Analysis in GMB Everywhere, page 6.",
                    "",
                    "Escalate if: The keyword is not obvious and the AI suggestion needs client sign-off. Route the proposed keyword to a manager/client to confirm. This is a designed check-in, not a failure.",
                ].join("\n"),
            },
            {
                key: "optimize-gbp-categories-and-profile",
                title: "Optimize GBP categories and profile completeness",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Tighten categories and fully complete the profile.",
                    "",
                    "Steps:",
                    "1. In GBP -> Edit Profile. Do not edit the business name. There is a high suspension risk.",
                    "2. Categories: use one main category and 0-3 subcategories, aiming for about two total, matching what top competitors use. Remove categories that overlap heavily or drift from the core service because both dilute ranking power.",
                    "3. Completeness: fill everything you can until the profile strength indicator is fully green. Minimum 3 of 5 profile features: full address, website, phone. Easy fourth: enable Online Appointments / link the Contact Us page.",
                    "",
                    "Done when: Categories are trimmed to 1-3, the profile indicator is green, and at least 3/5, ideally 4/5, features are present.",
                    "",
                    "SOP ref: Fixing the GBP -> Business Name / Category / Completing the Profile, pages 6-17.",
                    "",
                    "Escalate if: You believe the business name itself needs changing. Do not do it yourself; flag to a manager.",
                ].join("\n"),
            },
            {
                key: "optimize-gbp-services-and-descriptions",
                title: "Optimize GBP services and descriptions",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Maximize the service list and add descriptions to the top services.",
                    "",
                    "Tools: GMB Everywhere Category Finder, competitor GBPs, and AI. Grok works well.",
                    "",
                    "Steps:",
                    "1. Build a master service list: pull related services from GMB Everywhere Category Finder and copy services from the top-10 competitor GBPs into one document.",
                    "2. Clean it with the SOP's AI dedupe prompt. Remove exact and near-identical variants, keep one form, and do not reword. Prune anything irrelevant and prioritize by search volume.",
                    "3. If unsure whether the client offers something, compile the list and send the client email template from the SOP asking what they do not do.",
                    "4. Add all services to GBP, max 99, under the right category. Ask AI to categorize if there are multiple categories.",
                    "5. For the top 20 services, generate descriptions of 300 characters or less with AI and paste each in. Target 30+ services total, benchmarked to the top-10 average.",
                    "",
                    "Done when: Full deduped service list is live in GBP, aiming for 30+ services, and the top 20 have <=300-character descriptions.",
                    "",
                    "SOP ref: Services, pages 6-17. Includes the AI dedupe prompt and client email template.",
                    "",
                    "Escalate if: The client has not replied on which services they do not offer. Proceed with confident services, hold uncertain ones, and note it. Loop a manager only if the client is unresponsive and it is blocking.",
                ].join("\n"),
            },
            {
                key: "optimize-gbp-bookings-and-faq",
                title: "Optimize GBP bookings and FAQ",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Add the final two GBP boosters.",
                    "",
                    "Steps:",
                    "1. Bookings: in the GBP dashboard, link the Contact Us page. This gains another profile feature.",
                    "2. FAQ: ask AI for a few relevant Q&As for this niche and location, then add them to the profile.",
                    "",
                    "Done when: Bookings are linked and FAQs are added.",
                    "",
                    "SOP ref: Bookings / Add FAQ, pages 6-17.",
                    "",
                    "Escalate if: Nothing. This is straightforward.",
                ].join("\n"),
            },
            {
                key: "on-page-seo-basic",
                title: "On-page SEO basic",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Fix title, headings, NAP, and map on the website.",
                    "",
                    "Steps:",
                    "1. Title tag format: BEST + primary category + city + business name + primary services + near me, if room. Aim around 200 characters. The 60-character limit is a myth here. See the SOP example.",
                    "2. H1 = primary category + city. H2 = secondary categories + most relevant services from your GMB Everywhere research.",
                    "3. NAP consistent on homepage and footer sitewide; embed the GBP map on the homepage.",
                    "4. If you do not know how to edit these on the client's platform, ask AI how to do it for that specific CMS.",
                    "",
                    "Done when: Title/H1/H2 are updated to format, NAP is consistent sitewide, and map is embedded.",
                    "",
                    "SOP ref: Onpage SEO -> Basic, page 18+.",
                    "",
                    "Escalate if: You cannot access the site's editor, or the platform blocks the change even after asking AI. That is usually an access/permissions issue and a real reason to ping a manager.",
                ].join("\n"),
            },
            {
                key: "citations-basic",
                title: "Citations basic: the 80/20",
                description: [
                    "Stage: Basic",
                    "",
                    "Goal: Get the high-trust must-have listings live with consistent NAP.",
                    "",
                    "Platforms: Bing Places, Apple Business Connect, Foursquare, Yelp for US clients only, and Data Axle.",
                    "",
                    "Steps:",
                    "1. Set up or claim each profile with NAP exactly matching the website and GBP.",
                    "2. Verification emails usually need the client. Ask them to help verify.",
                    "3. Do 4-5 of these and the bulk of citation work is done.",
                    "",
                    "Done when: 4-5 core citations are submitted/claimed with matching NAP, and any pending client verification is noted.",
                    "",
                    "SOP ref: Citations -> The 80/20, page 24+.",
                    "",
                    "Escalate if: A platform needs client-side verification and the client is stalling, blocking completion.",
                ].join("\n"),
            },
            {
                key: "on-page-seo-advanced-content-and-structure",
                title: "On-page SEO advanced: content and structure",
                description: [
                    "Stage: Advanced - skip on first run",
                    "",
                    "Goal: Build out pages, topical authority, local authority, schema, and interlinking when the basics are not enough.",
                    "",
                    "Steps:",
                    "1. Schema: generate LocalBusiness schema via technicalseo.com generator and add it.",
                    "2. Topical authority: give each core service its own 1,000-2,500-word page. Build a /services hub and a subpage per service. Use the SOP's Topical Authority Services Page AI prompt. Follow the rank hierarchy: landing -> category -> service pages.",
                    "3. Local authority: add an Areas We Serve page and a subpage per area, starting with five. Use the SOP's Hyperlocal Landing Page AI prompt.",
                    "4. Interlinking: connect service pages and area pages with natural, varied anchor text. Service pages -> 2-4 area pages plus a We serve these areas list. Area pages -> 3-6 services. Homepage/contact -> all. Max 8-10 links per page, no repeated identical anchors, no irrelevant links, and do not dump everything in the footer. Click-test the links.",
                    "",
                    "Done when: Service and area pages are live with unique 1,000-2,500-word copy, schema is added, and interlinking is done per the SOP checklist and click-tested.",
                    "",
                    "SOP ref: Onpage SEO -> Advanced, page 18+. Both AI prompts and interlinking tables are there.",
                    "",
                    "Escalate if: The page volume needs another contractor, such as the landing-page specialist, or sign-off to publish many new pages. That is a resourcing/approval call, not an unclear step.",
                ].join("\n"),
            },
            {
                key: "citations-advanced",
                title: "Citations advanced",
                description: [
                    "Stage: Advanced - skip on first run",
                    "",
                    "Goal: Expand citations using competitor data and relevance signals.",
                    "",
                    "Steps:",
                    "1. SERP directories: search your keyword, scan the top-20 organic results, and note directories/lists you could get listed on. Google ranking them means Google sees them as relevant.",
                    "2. Competitor backlinks: open top competitors' GBPs -> More about -> see who links to them. Fill the same gaps.",
                    "3. AI suggestions: ask AI for relevant citation/backlink sources for the niche and location.",
                    "4. Extra sources: the SOP lists more, including Foursquare, Yell, Nextdoor, Waze, HotFrog, and Manta.",
                    "5. Paid option: buy citations via Leadsnap / FatJoe / Leadforge once volume justifies it, around $20/mo per client.",
                    "",
                    "Done when: Additional relevant citations are identified and submitted, and the paid option is flagged if worthwhile.",
                    "",
                    "SOP ref: Citations -> Finding Highest Opportunity + Additional Options, page 24+.",
                    "",
                    "Escalate if: A purchase/budget decision is needed for paid citations. That is spend approval; route to a manager.",
                ].join("\n"),
            },
            {
                key: "weekly-maintenance-and-client-habits",
                title: "Set up weekly maintenance and client habits",
                description: [
                    "Stage: Ongoing",
                    "",
                    "Goal: Stand up the recurring routine that keeps rankings climbing. Set this as a recurring task.",
                    "",
                    "Steps:",
                    "1. Weekly GBP posts: generate with AI, lightly edit, and publish.",
                    "2. Weekly geotagged photos: add or AI-generate images, then add geotags with GeoSetter (geosetter.de). Geotag toward the outskirts of the service area to push ranking there.",
                    "3. Client habits: tell the client to ask customers for reviews steadily and upload fresh photos of work/team directly to Google Maps weekly. IG/FB posting is a bonus.",
                    "",
                    "Done when: A recurring weekly schedule is running for posts and photos, and the client has been briefed on reviews and photos.",
                    "",
                    "SOP ref: Weekly Tings + Client Management, page 29.",
                    "",
                    "Escalate if: Nothing. This is routine.",
                ].join("\n"),
            },
            {
                key: "report-fake-black-hat-competitor-listing",
                title: "Report a fake or black-hat competitor listing",
                description: [
                    "Stage: Situational - only when a clear fake is blocking ranking",
                    "",
                    "Goal: Remove fake listings that are genuinely in the way. We are white-hat only.",
                    "",
                    "Steps:",
                    "1. Confirm it is fake: all-caps keyword-stuffed name, implausible location such as a tree surgeon in a shopping mall, or website with no address / only a phone number.",
                    "2. Be 100% sure it is not a real business before reporting. Bad reports get our future reports ignored, and we never hurt real businesses.",
                    "3. GBP -> Suggest an Edit -> Place is closed or not here -> add supporting evidence, such as a photo of the location interior. If the first attempt fails, have the client film a quick walk-by.",
                    "",
                    "Done when: Report is filed with evidence, or you have judged it is not clearly fake and left it alone.",
                    "",
                    "SOP ref: Black Hat vs White Hat, page 29+.",
                    "",
                    "Escalate if: You are not certain it is fake. Do not report; check with a manager first.",
                ].join("\n"),
            },
        ],
    },
}

export function getModuleKeysForServices(serviceKeys: string[]) {
    const moduleKeys = new Set<string>(["general-info"])

    for (const serviceKey of serviceKeys) {
        const service = SERVICES[serviceKey]

        for (const moduleKey of service?.requiredModuleKeys ?? []) {
            moduleKeys.add(moduleKey)
        }
    }

    return [...moduleKeys]
}
