import { IntegrationProvider } from "@/lib/workspace-integrations"

type Connection = { provider: IntegrationProvider; enabled: boolean; mode: string; config_hint: Record<string, string | null> }
type Props = { connections: Connection[]; action: (provider: IntegrationProvider, formData: FormData) => Promise<void>; verifyAction: (provider: IntegrationProvider) => Promise<void>; canManage: boolean; showHeader?: boolean }

const fields: Record<IntegrationProvider, Array<[string, string, string]>> = {
    stripe: [["secret_key", "Stripe secret key", "sk_live_… or sk_test_…"], ["webhook_secret", "Webhook signing secret", "whsec_…"], ["default_currency", "Default currency", "usd"]],
    meta_whatsapp: [["access_token", "Meta access token", "Permanent access token"], ["phone_number_id", "WhatsApp phone number ID", "From Meta"], ["webhook_verify_token", "Webhook verification token", "Choose a long random value"], ["consent_template_name", "Consent template name", "Template name"], ["consent_template_language", "Template language", "en_US"]],
}
const titles: Record<IntegrationProvider, string> = { stripe: "Stripe", meta_whatsapp: "Meta WhatsApp" }

function detail(connection: Connection) {
    const hint = connection.config_hint
    if (connection.provider === "stripe") return [hint.account_id, hint.mode, hint.currency].filter(Boolean).join(" · ")
    if (connection.provider === "meta_whatsapp") return [hint.display_phone_number ?? hint.phone_number_id, hint.verified_name ?? hint.template].filter(Boolean).join(" · ")
    return ""
}

export function WorkspaceConnections({ connections, action, verifyAction, canManage, showHeader = true }: Props) {
    return <section className={showHeader ? "mt-8" : ""}>{showHeader && <><h2 className="text-lg font-semibold">Connections</h2><p className="mt-1 text-sm text-neutral-400">Each workspace keeps its own credentials. Secrets are encrypted and never shown again.</p></>}<div className={`${showHeader ? "mt-4 " : ""}grid gap-4 lg:grid-cols-3`}>{connections.map((connection) => { const verified = Boolean(connection.config_hint.verified_at); const status = connection.mode === "platform_legacy" ? "Managed platform connection" : verified ? "Connection verified" : connection.enabled ? "Configured — activation in progress" : "Not configured"; return <details key={connection.provider} className="rounded-2xl border border-neutral-800 bg-neutral-900 p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><p className="font-medium">{titles[connection.provider]}</p><p className={`mt-1 text-sm ${connection.enabled ? "text-emerald-300" : "text-neutral-500"}`}>{status}</p>{detail(connection) && <p className="mt-1 text-xs text-neutral-500">{detail(connection)}</p>}</div>{connection.mode !== "platform_legacy" && canManage && <span className="text-sm text-neutral-400">Edit</span>}</summary>{connection.mode === "platform_legacy" ? <p className="mt-5 text-sm leading-6 text-neutral-400">This workspace continues to use the existing managed connection. Its credentials are intentionally not editable here.</p> : canManage ? <div className="mt-5 space-y-4"><form action={action.bind(null, connection.provider)} className="space-y-3">{fields[connection.provider].map(([name, label, placeholder]) => <label key={name} className="block text-sm text-neutral-300">{label}<input name={name} type={name.includes("token") || name.includes("secret") || name === "api_token" ? "password" : "text"} placeholder={placeholder} className="mt-1.5 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-2 text-white" /></label>)}<button className="w-full rounded-lg bg-white px-3 py-2 text-sm font-medium text-black">Save {titles[connection.provider]} credentials</button></form>{connection.enabled && <form action={verifyAction.bind(null, connection.provider)}><button className="w-full rounded-lg border border-neutral-700 px-3 py-2 text-sm text-neutral-200">Verify connection</button></form>}<p className="text-xs leading-5 text-neutral-500">Saving credentials does not activate an unfinished provider workflow. Verify confirms the provider accepts these credentials.</p></div> : <p className="mt-5 text-sm leading-6 text-neutral-500">Only the workspace owner can manage this connection.</p>}</details>})}</div></section>
}
