-- Transactional integration checks. Run as postgres after the migration.
-- All fixtures and writes are isolated in a disposable workspace and rolled back.
begin;
set local lock_timeout='5s';
set local statement_timeout='30s';
do $$
declare
 w uuid:=gen_random_uuid(); outside_w uuid:=gen_random_uuid();
 owner_id uuid:=gen_random_uuid(); seller_id uuid:=gen_random_uuid(); manager_id uuid:=gen_random_uuid(); staff_id uuid:=gen_random_uuid(); alternate_id uuid:=gen_random_uuid();
 service_a uuid:=gen_random_uuid(); service_b uuid:=gen_random_uuid(); client_a uuid:=gen_random_uuid(); client_b uuid:=gen_random_uuid(); t uuid; result jsonb; rejected boolean;
begin
 insert into auth.users(id,email) values(owner_id,'delivery-owner-'||owner_id||'@example.invalid'),(seller_id,'delivery-seller-'||seller_id||'@example.invalid'),(manager_id,'delivery-manager-'||manager_id||'@example.invalid'),(staff_id,'delivery-staff-'||staff_id||'@example.invalid'),(alternate_id,'delivery-alternate-'||alternate_id||'@example.invalid');
 insert into public.workspaces(id,name,slug) values(w,'Delivery test','delivery-'||w),(outside_w,'Other workspace','delivery-'||outside_w);
 insert into public.workspace_memberships(workspace_id,user_id,role) values(w,owner_id,'owner'),(w,seller_id,'staff'),(w,manager_id,'staff'),(w,staff_id,'staff'),(w,alternate_id,'staff');
 assert public.workspace_user_can_sell(w,owner_id), 'New owner needs a usable empty-workspace setup';
 assert not public.workspace_user_can_sell(w,staff_id), 'Staff authority unexpectedly grants selling';
 assert exists(select 1 from public.workspace_memberships where workspace_id=w and user_id=staff_id), 'Staff must be allowed to join without a service';
 perform public.save_workspace_operations(w,owner_id,jsonb_build_array(jsonb_build_object('userId',seller_id,'canSell',true,'canManage',false),jsonb_build_object('userId',manager_id,'canSell',false,'canManage',true)),jsonb_build_object('seller',jsonb_build_array('relationships.view'),'manager',jsonb_build_array('relationships.view','onboarding.manage','fulfilment.manage')));
 rejected:=false;
 begin perform public.save_workspace_operations(w,staff_id,'[]','{}'); exception when others then rejected:=true; end;
 assert rejected, 'Staff changed operational settings';
 insert into public.onboarding_services(id,workspace_id,internal_code) values(service_a,w,'delivery-a'),(service_b,w,'delivery-b');
 perform public.set_service_delivery_users(w,owner_id,service_a,array[staff_id,alternate_id,owner_id]);
 perform public.set_service_delivery_users(w,owner_id,service_b,array[staff_id,manager_id]);
 assert (select count(*) from public.workspace_member_service_access where workspace_id=w and service_id=service_a)=3, 'Eligibility must support multiple users and every workspace role';
 insert into public.relationships(id,workspace_id,primary_person_name,business_name,lifecycle_phase,source_metadata) values(client_a,w,'Test client','Same company','potential_client','{"is_test":true}'),(client_b,w,'Test client two','Same company','potential_client','{"is_test":true}');
 assert public.workspace_user_can_access_relationship(w,client_a,seller_id), 'Seller cannot open an unclaimed POS';
 assert not public.workspace_user_can_access_relationship(w,client_a,staff_id), 'Service eligibility leaked an unassigned relationship';
 result:=public.begin_relationship_pos(w,client_a,seller_id);
 assert result->>'seller_user_id'=seller_id::text, 'POS did not record its initiator';
 assert public.begin_relationship_pos(w,client_a,seller_id)=result, 'POS resume changed attribution or version';
 rejected:=false;
 begin perform public.begin_relationship_pos(w,client_a,owner_id); exception when others then rejected:=true; end;
 assert rejected, 'Another seller took over a started POS';
 update public.relationships set fulfilment_manager_user_id=manager_id where id=client_a;
 insert into public.relationship_services(workspace_id,relationship_id,service_key,service_id,assignee_user_id) values(w,client_a,'delivery-a',service_a,staff_id),(w,client_a,'delivery-b',service_b,staff_id);
 perform public.validate_relationship_delivery_team(w,client_a);
 assert public.workspace_user_can_access_relationship(w,client_a,staff_id), 'Selected fulfilment staff cannot access their client';
 assert not public.workspace_user_can_access_relationship(w,client_a,alternate_id), 'Unselected eligible staff can access client';
 assert public.client_conversation_can_access(w,client_a,seller_id) and public.client_conversation_can_access(w,client_a,manager_id), 'Seller or manager missing from client chat';
 assert not public.client_conversation_can_access(w,client_a,staff_id) and not public.client_conversation_can_access(w,client_a,owner_id), 'Client chat is visible to nonparticipants';
 assert not public.client_conversation_can_access(outside_w,client_a,seller_id), 'Conversation crosses workspace boundary';
 update public.relationships set lifecycle_phase='sold' where id=client_a;
 select id into t from public.workspace_teams where relationship_id=client_a;
 assert t is not null, 'Sale did not create a client delivery team';
 assert public.create_relationship_delivery_team(w,client_a)=t, 'Retry created another delivery team';
 assert (select count(*) from public.workspace_team_members where team_id=t)=3, 'Overlapping service assignments duplicated team membership';
 assert exists(select 1 from public.workspace_native_conversations where team_id=t), 'No internal group conversation created';
 rejected:=false;
 begin update public.relationships set seller_user_id=owner_id where id=client_a; exception when others then rejected:=true; end;
 assert rejected, 'Sold seller changed';
 rejected:=false;
 begin update public.relationships set fulfilment_manager_user_id=owner_id where id=client_a; exception when others then rejected:=true; end;
 assert rejected, 'Sold manager changed';
 rejected:=false;
 begin update public.relationship_services set assignee_user_id=alternate_id where relationship_id=client_a; exception when others then rejected:=true; end;
 assert rejected, 'Sold fulfilment staff changed';
 rejected:=false;
 begin delete from public.relationship_services where relationship_id=client_a; exception when others then rejected:=true; end;
 assert rejected, 'Sold services deleted';
 rejected:=false;
 begin perform public.set_client_chat_members(w,client_a,seller_id,array[staff_id]); exception when others then rejected:=true; end;
 assert rejected, 'Seller modified client-chat participation';
 rejected:=false;
 begin perform public.set_client_chat_members(w,client_a,manager_id,array[alternate_id]); exception when others then rejected:=true; end;
 assert rejected, 'Manager added a person outside this client team';
 perform public.set_client_chat_members(w,client_a,manager_id,array[staff_id]);
 assert public.client_conversation_can_access(w,client_a,staff_id), 'Manager could not include selected fulfilment staff';
 perform public.set_client_chat_members(w,client_a,manager_id,'{}');
 assert not public.client_conversation_can_access(w,client_a,staff_id), 'Removed chat participant still has access';
 assert exists(select 1 from public.workspace_team_members where team_id=t and user_id=staff_id), 'Client-chat removal changed the delivery team';
 perform public.set_service_delivery_users(w,owner_id,service_a,array[alternate_id]);
 assert exists(select 1 from public.relationship_services where relationship_id=client_a and assignee_user_id=staff_id), 'Eligibility update changed existing allocations';
 rejected:=false;
 begin delete from public.workspace_memberships where workspace_id=w and user_id=staff_id; exception when others then rejected:=true; end;
 assert rejected, 'Offboarding stranded an active client';
 -- Invalid sale leaves no partial team or lifecycle update.
 perform public.begin_relationship_pos(w,client_b,seller_id);
 update public.relationships set fulfilment_manager_user_id=manager_id where id=client_b;
 insert into public.relationship_services(workspace_id,relationship_id,service_key,service_id,assignee_user_id) values(w,client_b,'delivery-a',service_a,staff_id);
 rejected:=false;
 begin update public.relationships set lifecycle_phase='sold' where id=client_b; exception when others then rejected:=true; end;
 assert rejected, 'Sale accepted ineligible service allocation';
 assert not exists(select 1 from public.workspace_teams where relationship_id=client_b), 'Rejected sale left a partial team';
 update public.relationship_services set assignee_user_id=alternate_id where relationship_id=client_b;
 update public.relationships set lifecycle_phase='sold' where id=client_b;
 assert (select count(*) from public.workspace_teams where workspace_id=w and name='Team: Same company')=2, 'Two clients sharing a company name collided';
 assert (select count(*) from public.client_conversation_rosters(w,seller_id))=2, 'Batched participant roster differs from access check';
end $$;
select 'PASS: empty workspace, overlapping roles, eligibility, POS ownership, sale validation, immutable teams, scoped conversations, manager participation, and duplicate names' as result;
rollback;
