'use client'
import { useState } from 'react'
import Link from '@/components/workspace/WorkspaceLink'
import { PanelTabHeader } from '@/components/panel/PanelTabHeader'
import { List,ListItem,ListPrimaryRow,ListSecondaryRow } from '@/components/list/List'
import { CenteredDialog } from '@/components/ui/CenteredDialog'
import { Status } from '@/components/ui'
type Dispute={id:string;work_item_id:string;reason:string;note:string;status:string;can_review:boolean;assessment:{summary:string;suggestion:string}|null;resolution:string|null;snapshot:{title:string;instructions:string|null};conversation_id:string}
type Outcome={id:string;work_item_id:string;active_seconds:number;corrected_minutes:number|null;estimate_minutes:number|null;met_target:boolean|null;valid_sample:boolean}
type Data={disputes:Dispute[];outcomes:Outcome[];preferences:{timezone:string;verbosity:number}|null}
const button='min-h-11 rounded-lg border border-neutral-700 px-3 py-2 text-sm hover:bg-neutral-800 disabled:opacity-50'
export function QueueFeedback({data,userId,workspaceSlug}:{data:Data;userId:string;workspaceSlug:string}){
 const [state,setState]=useState(data),[selected,setSelected]=useState<Dispute|null>(null),[resolution,setResolution]=useState(''),[approved,setApproved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[timezone,setTimezone]=useState(data.preferences?.timezone??'Europe/Dublin'),[time,setTime]=useState<Outcome|null>(null),[minutes,setMinutes]=useState('')
 async function openDispute(d:Dispute){setSelected(d);setResolution('');setApproved(false);setError('');setBusy(true);try{const r=await fetch(`/api/workspaces/${workspaceSlug}/queue/feedback?id=${d.id}`,{headers:{'x-workspace-user':userId},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error('Could not load original dispute');const detail=await r.json();setSelected(current=>current?.id===d.id?detail:current)}catch(e){setError(e instanceof Error?e.message:'Could not load dispute')}finally{setBusy(false)}}
 async function save(body:object){if(busy)return;setBusy(true);setError('');try{const response=await fetch(`/api/workspaces/${workspaceSlug}/queue/feedback`,{method:'POST',headers:{'Content-Type':'application/json','x-workspace-user':userId},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const result=await response.json();if(!response.ok)throw new Error(result.error);setSelected(null);setTime(null);const fresh=await fetch(`/api/workspaces/${workspaceSlug}/queue/feedback`,{headers:{'x-workspace-user':userId},cache:'no-store',signal:AbortSignal.timeout(30000)});if(!fresh.ok)throw new Error('Saved, but refresh failed. Reload this page.');const next=await fresh.json();if(next.userId!==userId)throw new Error('Your session changed');setState(next)}catch(e){setError(e instanceof Error?e.message:'Could not confirm feedback')}finally{setBusy(false)}}
 return <><PanelTabHeader title="Queue feedback" description="Review disputes and your recorded feedback." actions={<Link className={button} href={`/${workspaceSlug}/queue`}>Work Queue</Link>}/>{error?<p role="alert" className="my-3 text-sm text-red-200">{error}</p>:null}
 <List>{state.disputes.map(d=><ListItem key={d.id}><ListPrimaryRow><button className="min-h-11 flex-1 text-left" onClick={()=>void openDispute(d)}>{d.snapshot.title}</button><Status label={d.status==='open'?'Disputed':'Resolved'} tone={d.status==='open'?'yellow':'green'}/></ListPrimaryRow><ListSecondaryRow><span>{d.reason}</span></ListSecondaryRow></ListItem>)}{!state.disputes.length?<p className="p-4 text-sm text-neutral-400">No disputes available.</p>:null}</List>
 <section className="my-6 space-y-3"><h2 className="font-semibold">Your preferences</h2><p className="text-sm text-neutral-400">Guidance: {(state.preferences?.verbosity??0)<0?'More concise':(state.preferences?.verbosity??0)>0?'More explanation':'Standard'}. Changes require three consistent, approved preferences. Required steps remain intact.</p><label className="block text-sm">Day-boundary timezone<input value={timezone} onChange={e=>setTimezone(e.target.value)} className="ml-3 rounded border border-neutral-700 bg-neutral-900 p-2"/></label><div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>void save({action:'preferences',timezone})}>Save timezone</button><button className={button} disabled={busy} onClick={()=>void save({action:'preferences',reset:true})}>Reset guidance preferences</button></div></section>
 <h2 className="mb-3 font-semibold">Recent completion feedback</h2><List>{state.outcomes.map(o=><ListItem key={o.id}><ListPrimaryRow><Link href={`/${workspaceSlug}/work-items/${o.work_item_id}`} className="flex-1">Completed work · {o.work_item_id.slice(0,8)}</Link><button className={button} onClick={()=>{setTime(o);setMinutes(String(o.corrected_minutes??Math.round(o.active_seconds/60)))}}>Correct active time</button></ListPrimaryRow><ListSecondaryRow><span>{o.corrected_minutes??Math.round(o.active_seconds/60)} active min · {o.estimate_minutes??'Unknown'} estimated · {o.met_target===null?'No priority window recorded':o.met_target?'Completed within priority window':'Priority window exceeded'}{!o.valid_sample?' · Excluded from calibration':''}</span></ListSecondaryRow></ListItem>)}</List>
 {selected?<CenteredDialog title="Review dispute" busy={busy} onClose={()=>setSelected(null)} footer={selected.can_review&&selected.status==='open'?<button className={button} disabled={busy||resolution.trim().length<5} onClick={()=>void save({action:'resolve',id:selected.id,resolution,approved})}>Resolve dispute</button>:undefined}><h2 className="font-medium">{selected.snapshot.title}</h2><p className="mt-3 text-sm">{selected.reason}</p><p className="mt-2 whitespace-pre-wrap text-sm text-neutral-300">{selected.note}</p><Link className="mt-3 block underline" href={`/${workspaceSlug}/work-items/${selected.work_item_id}`}>Open current instructions</Link><details className="mt-3 text-sm"><summary>Original instructions</summary><p className="mt-2 whitespace-pre-wrap">{selected.snapshot.instructions}</p></details>{selected.assessment?<div className="mt-4 text-sm"><strong>AI review suggestion</strong><p>{selected.assessment.summary}</p><p className="mt-2">{selected.assessment.suggestion}</p></div>:<p className="mt-3 text-sm text-neutral-500">AI review is pending or unavailable. You can review the dispute now.</p>}{selected.can_review&&selected.status==='open'?<><label className="mt-4 block text-sm">Resolution<textarea className="mt-2 min-h-24 w-full rounded border border-neutral-700 bg-neutral-900 p-3" value={resolution} onChange={e=>setResolution(e.target.value)} maxLength={3000}/></label><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>Approve this resolution as guidance for future work in this client/service scope.</label><p className="mt-2 text-xs text-neutral-500">Correct the work item first if needed. Resolving releases the dispute; dependencies and service readiness still apply.</p></>:<p className="mt-3 text-sm">{selected.resolution}</p>}{error?<p role="alert" className="mt-3 text-red-200">{error}</p>:null}</CenteredDialog>:null}
 {time?<CenteredDialog title="Correct active time" busy={busy} onClose={()=>setTime(null)} footer={<button className={button} disabled={busy||!Number.isInteger(Number(minutes))||Number(minutes)<1} onClick={()=>void save({action:'correct-time',id:time.id,minutes:Number(minutes)})}>Save active minutes</button>}><p className="text-sm text-neutral-400">Exclude breaks and waiting. Corrections are available for seven days, before a sample has been used for calibration.</p><input type="number" min={1} max={4800} value={minutes} onChange={e=>setMinutes(e.target.value)} className="mt-4 rounded border border-neutral-700 bg-neutral-900 p-3"/>{error?<p role="alert" className="mt-3 text-red-200">{error}</p>:null}</CenteredDialog>:null}
 </>
}
