"use client"
import Link from "next/link"
import { FormEvent, useEffect, useState } from "react"
import { createSupabaseBrowserClient } from "@/lib/supabase/browser"
const usernamePattern = /^[a-z0-9](?:[a-z0-9-]{1,28}[a-z0-9])?$/
export default function SignUpPage() {
 const [invite,setInvite]=useState<string|null>(null),[email,setEmail]=useState(""),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(false),[sent,setSent]=useState(false)
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setInvite(q.get("invite"));setEmail(q.get("email")??"")},[])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError(null);const f=new FormData(e.currentTarget);const username=String(f.get("username")??"").trim().toLowerCase();if(!usernamePattern.test(username)){setError("Use 3–30 lowercase letters, numbers, or hyphens.");setLoading(false);return}const next=invite?`/mfa?next=${encodeURIComponent(`/invites/accept?token=${invite}`)}`:"/login";const {error}=await createSupabaseBrowserClient().auth.signUp({email,password:String(f.get("password")??""),options:{data:{username},emailRedirectTo:`${window.location.origin}/auth/callback?next=${encodeURIComponent(next)}`}});if(error){setError(error.message);setLoading(false);return}setSent(true);setLoading(false)}
 if(sent)return <main className="flex min-h-screen items-center justify-center bg-neutral-950 px-6 text-white"><div className="w-full max-w-sm rounded-2xl border border-neutral-800 bg-neutral-900 p-7"><p className="text-sm text-neutral-400">Betelgeze</p><h1 className="mt-3 text-2xl font-semibold">Check your email</h1><p className="mt-3 text-neutral-300">Confirm your email to finish setting up your account and two-factor authentication.</p></div></main>
 return <main className="flex min-h-screen items-center justify-center bg-neutral-950 px-6 text-white"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl border border-neutral-800 bg-neutral-900 p-7"><p className="text-sm text-neutral-400">Betelgeze</p><h1 className="mt-3 text-2xl font-semibold">{invite?"Join your workspace":"Create your account"}</h1><label className="mt-6 block text-sm">Username<input name="username" required className="mt-2 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-3" /></label><label className="mt-4 block text-sm">Email<input value={email} onChange={e=>setEmail(e.target.value)} name="email" type="email" required readOnly={Boolean(invite)} className="mt-2 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-3" /></label><label className="mt-4 block text-sm">Password<input name="password" type="password" minLength={12} required className="mt-2 w-full rounded-lg border border-neutral-700 bg-neutral-950 px-3 py-3" /></label>{error&&<p className="mt-4 text-sm text-red-400">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-lg bg-white px-4 py-3 font-medium text-black">{loading?"Creating…":"Create account"}</button><p className="mt-5 text-sm text-neutral-400">Already registered? <Link className="text-white underline" href={invite?`/login?invite=${invite}`:"/login"}>Log in</Link></p></form></main>
}
