-- Leadgen contractor v1 source catalog.
-- Run first.

insert into public.leadgen_source_catalog (
    source_key,
    label,
    family,
    source_points,
    owner_identity_points,
    owner_phone_points,
    business_support_points,
    access_method,
    free_status,
    implementation_status,
    run_stage,
    enabled,
    rate_limit_ms,
    coverage,
    metadata
) values
    (
        'state_license.tx.plumbing',
        'Texas plumbing examiners',
        'licensing',
        3,
        3,
        3,
        2,
        'public_csv',
        'free',
        'active',
        'candidate_investigation',
        true,
        1200,
        '{"states":["TX"],"industries":["plumbers"]}'::jsonb,
        '{"adapter":"tsbpe_rmp_csv","source_url":"https://tsbpe.texas.gov/download-csv/RMP/","phone_note":"Responsible Master Plumber rows expose license holder name, company, and phone. Betelgeze treats this as owner/principal phone evidence."}'::jsonb
    ),
    (
        'state_license.fl.dbpr',
        'Florida DBPR construction',
        'licensing',
        3,
        3,
        0,
        2,
        'public_csv',
        'free',
        'active',
        'candidate_investigation',
        true,
        1800,
        '{"states":["FL"],"industries":["general_contractors","home_builders","remodellers","roofers","hvac_contractors","plumbers","pool_builders","solar_installers","flooring_contractors","lighting_contractors"]}'::jsonb,
        '{"adapter":"dbpr_construction_csv","source_url":"https://www2.myfloridalicense.com/sto/file_download/extracts/CONSTRUCTIONLICENSE_1.csv","phone_note":"The construction feed proves qualifier/person and business, but normally does not expose a phone number."}'::jsonb
    ),
    (
        'state_license.fl.electrical',
        'Florida DBPR electrical records',
        'licensing',
        3,
        3,
        0,
        2,
        'public_csv',
        'free',
        'active',
        'candidate_investigation',
        true,
        1500,
        '{"states":["FL"],"industries":["electricians","lighting_contractors","solar_installers","pool_builders","hvac_contractors","general_contractors"]}'::jsonb,
        '{"adapter":"dbpr_electrical_csv","source_url":"https://www2.myfloridalicense.com/sto/file_download/extracts/lic08el.csv","phone_note":"The electrical feed proves licensee/person and business, but normally does not expose a phone number."}'::jsonb
    ),
    (
        'state_license.nc.general_contractors',
        'North Carolina general contractor licensing',
        'licensing',
        3,
        3,
        3,
        2,
        'public_html',
        'free',
        'active',
        'candidate_investigation',
        true,
        1500,
        '{"states":["NC"],"industries":["concrete_contractors","deck_builders","fencing_contractors","general_contractors","hardscaping_contractors","home_builders","insulation_contractors","kitchen_remodelling","masonry_contractors","patio_contractors","pool_builders","remodellers","restoration_companies","roofers","siding_contractors","window_and_door_contractors"]}'::jsonb,
        '{"adapter":"nclbgc_public_search","search_url":"https://portal.nclbgc.org/Public/_Search/","detail_url":"https://portal.nclbgc.org/Public/_ShowAccountDetails/"}'::jsonb
    ),
    (
        'permits.tx.dallas',
        'Dallas active contractor registrations',
        'permits',
        3,
        0,
        0,
        3,
        'public_api',
        'free',
        'active',
        'candidate_investigation',
        true,
        900,
        '{"states":["TX"],"cities":["Dallas"]}'::jsonb,
        '{
            "adapter":"socrata_public_records",
            "domain":"www.dallasopendata.com",
            "dataset_id":"jhgk-eg9m",
            "dataset_name":"Active Contractors",
            "provenance_url":"https://www.dallasopendata.com/d/jhgk-eg9m",
            "claim_profile":"city_contractor_registration",
            "person_role":"registered_contractor",
            "query_limit":15,
            "owner_identity_points_on_match":0,
            "owner_phone_points_on_match":0,
            "business_support_points_on_match":3,
            "default_address":{"city":"Dallas","state":"TX"},
            "field_map":{"business_name":["contractor"],"contractor_name":["contractor"],"phone":["phone"],"address":["address"],"record_type":["registration_type"],"additional_match_name":["city_state"]}
        }'::jsonb
    ),
    (
        'permits.tx.austin',
        'Austin ROW contractor licences',
        'permits',
        3,
        0,
        0,
        2,
        'public_api',
        'free',
        'active',
        'candidate_investigation',
        true,
        900,
        '{"states":["TX"],"cities":["Austin"]}'::jsonb,
        '{
            "adapter":"socrata_public_records",
            "domain":"datahub.austintexas.gov",
            "dataset_id":"8d92-wsiw",
            "dataset_name":"Active Right of Way Contractor License Holders",
            "provenance_url":"https://datahub.austintexas.gov/d/8d92-wsiw",
            "claim_profile":"city_contractor_license_activity",
            "query_limit":15,
            "owner_identity_points_on_match":0,
            "owner_phone_points_on_match":0,
            "business_support_points_on_match":2,
            "default_address":{"city":"Austin","state":"TX"},
            "field_map":{"business_name":["contractor_name"],"contractor_name":["contractor_name"],"record_id":["license_number"],"status":["expiration_date"],"record_type":["license_number"]}
        }'::jsonb
    ),
    (
        'permits.fl.orlando',
        'Orlando permit applications',
        'permits',
        3,
        2,
        2,
        3,
        'public_api',
        'free',
        'active',
        'candidate_investigation',
        true,
        900,
        '{"states":["FL"],"cities":["Orlando"]}'::jsonb,
        '{
            "adapter":"socrata_public_records",
            "domain":"data.cityoforlando.net",
            "dataset_id":"ryhf-m453",
            "dataset_name":"Permit Applications",
            "provenance_url":"https://data.cityoforlando.net/d/ryhf-m453",
            "claim_profile":"city_permit_contractor_contact",
            "person_role":"permit_contractor_or_qualifier",
            "query_limit":15,
            "owner_identity_points_on_match":2,
            "owner_phone_points_on_match":2,
            "business_support_points_on_match":3,
            "default_address":{"city":"Orlando","state":"FL"},
            "field_map":{"business_name":["contractor_name","private_provider_company_name"],"contractor_name":["contractor"],"owner_name":["private_provider_qualifier_name"],"phone":["contractor_phone_number"],"address":["contractor_address","permit_address"],"record_id":["permit_number"],"status":["application_status"],"record_type":["application_type","worktype"],"geopoint":["geocoded_column"],"additional_match_name":["project_name","property_owner_name","parcel_owner_name"]}
        }'::jsonb
    ),
    (
        'registry.fl.orlando_btr',
        'Orlando business tax receipts',
        'registries',
        3,
        3,
        3,
        3,
        'public_api',
        'free',
        'active',
        'candidate_investigation',
        true,
        900,
        '{"states":["FL"],"cities":["Orlando"]}'::jsonb,
        '{
            "adapter":"socrata_public_records",
            "domain":"data.cityoforlando.net",
            "dataset_id":"7388-4re5",
            "dataset_name":"Business Tax Receipts",
            "provenance_url":"https://data.cityoforlando.net/d/7388-4re5",
            "claim_profile":"city_business_tax_owner_phone",
            "identity_claim_kind":"owner_identity",
            "person_role":"business_owner",
            "query_limit":15,
            "owner_identity_points_on_match":3,
            "owner_phone_points_on_match":3,
            "business_support_points_on_match":3,
            "default_address":{"city":"Orlando","state":"FL"},
            "field_map":{"business_name":["business_name"],"owner_name":["business_owner_name"],"phone":["phone"],"address":["business_address","business_mailing_address"],"record_id":["case_number"],"status":["license_status"],"record_type":["license_type","license_category"],"geopoint":["geocoded_column"],"additional_match_name":["business_email"]}
        }'::jsonb
    ),
    (
        'permits.ca.los_angeles',
        'Los Angeles permits',
        'permits',
        3,
        3,
        0,
        3,
        'public_api',
        'free',
        'active',
        'candidate_investigation',
        true,
        900,
        '{"states":["CA"],"cities":["Los Angeles"]}'::jsonb,
        '{
            "adapter":"socrata_public_records",
            "domain":"data.lacity.org",
            "dataset_id":"g6eu-kwix",
            "dataset_name":"Permits Since 2018",
            "provenance_url":"https://data.lacity.org/d/g6eu-kwix",
            "claim_profile":"permit_license_principal",
            "person_role":"license_principal",
            "query_limit":15,
            "owner_identity_points_on_match":3,
            "owner_phone_points_on_match":0,
            "business_support_points_on_match":3,
            "default_address":{"city":"Los Angeles","state":"CA"},
            "field_map":{"business_name":["contractors_business_name","applicant_business_name"],"contractor_name":["contractors_business_name"],"record_id":["pcis_permit","reference_old_permit"],"status":["latest_status"],"record_type":["permit_type","permit_sub_type","permit_category"],"address":["contractor_address"],"city":["contractor_city"],"state":["contractor_state"],"postcode":["zip_code"],"geopoint":["location_1"],"additional_match_name":["work_description"]}
        }'::jsonb
    ),
    (
        'regulated.epa_echo',
        'EPA ECHO facility search',
        'regulated',
        2,
        0,
        0,
        2,
        'public_api',
        'free',
        'active',
        'candidate_investigation',
        true,
        1200,
        '{"countries":["US"],"industries":["waste_disposal","cleaning_companies","restoration_companies","water_well_services"]}'::jsonb,
        '{"adapter":"epa_echo_cwa_facility_info","query_limit":10,"note":"Useful validation support for waste, remediation, septic/well, and industrial cleaning-adjacent businesses."}'::jsonb
    )
on conflict (source_key)
do update set
    label = excluded.label,
    family = excluded.family,
    source_points = excluded.source_points,
    owner_identity_points = excluded.owner_identity_points,
    owner_phone_points = excluded.owner_phone_points,
    business_support_points = excluded.business_support_points,
    access_method = excluded.access_method,
    free_status = excluded.free_status,
    implementation_status = excluded.implementation_status,
    run_stage = excluded.run_stage,
    enabled = excluded.enabled,
    rate_limit_ms = excluded.rate_limit_ms,
    coverage = excluded.coverage,
    metadata = public.leadgen_source_catalog.metadata || excluded.metadata,
    updated_at = now();
