/** Preserve validators and byte-range semantics across the authenticated proxy. */
export function communicationMediaRequestHeaders(request: Request, preview: boolean) {
    const headers: Record<string, string> = {}
    for (const name of ["if-none-match", "if-modified-since", ...(!preview ? ["range", "if-range"] : [])]) {
        const value = request.headers.get(name)
        if (value) headers[name] = value
    }
    return headers
}

export function communicationMediaStatusIsValid(status: number) {
    return (status >= 200 && status < 300) || status === 304 || status === 416
}

function discardMediaResponse(response: Response) {
    // Next.js tees fetch responses and retains a sibling. Cancellation of our
    // branch can wait for that sibling forever; cleanup must not gate fallback.
    void response.body?.cancel().catch(() => undefined)
}

/** Authorize before calling. A prepared preview needs only one storage request. */
export async function loadCommunicationMediaRepresentation(input: {
    originalPath: string
    previewPath: string
    preview: boolean
    method: "HEAD" | "GET"
    load: (path: string, signal?: AbortSignal) => Promise<Response>
    prepare: (signal: AbortSignal) => Promise<boolean | Response>
    previewTimeoutMs?: number
}) {
    if (input.preview) {
        const controller = new AbortController()
        const { signal } = controller
        let timer: ReturnType<typeof setTimeout> | undefined
        const deadline = new Promise<null>((resolve) => {
            timer = setTimeout(() => {
                controller.abort(new Error("Media preview timed out"))
                resolve(null)
            }, input.previewTimeoutMs ?? 10_000)
        })
        const preview = (async () => {
            let response = await input.load(input.previewPath, signal)
            if (signal.aborted) { discardMediaResponse(response); return null }
            if (response.status === 404) {
                discardMediaResponse(response)
                // HEAD never creates an object. Only repair an authorized 404.
                const prepared = input.method === "GET" && await input.prepare(signal).catch(() => false)
                if (signal.aborted || !prepared) {
                    if (prepared instanceof Response) discardMediaResponse(prepared)
                    return null
                }
                // Generated bytes are already in memory; no second download.
                response = prepared instanceof Response ? prepared : await input.load(input.previewPath, signal)
                if (signal.aborted) { discardMediaResponse(response); return null }
            }
            return { response, deliveryPath: input.previewPath }
        })().catch((error: unknown) => {
            if (signal.aborted) return null
            throw error
        })
        try {
            const result = await Promise.race([preview, deadline])
            if (result) return result
        } finally { clearTimeout(timer) }
    }
    // Give the original an independent lifetime, preserving large-file streams
    // and byte-range delivery when a thumbnail expires or cannot be prepared.
    return { response: await input.load(input.originalPath), deliveryPath: input.originalPath }
}
