/** Preserve validators and byte-range semantics across the authenticated proxy. */
export function communicationMediaRequestHeaders(request: Request, preview: boolean) {
    const headers: Record<string, string> = {}
    for (const name of ["if-none-match", "if-modified-since", ...(!preview ? ["range", "if-range"] : [])]) {
        const value = request.headers.get(name)
        if (value) headers[name] = value
    }
    return headers
}

export function communicationMediaStatusIsValid(status: number) {
    return (status >= 200 && status < 300) || status === 304 || status === 416
}

/** Authorize before calling. A prepared preview needs only one storage request. */
export async function loadCommunicationMediaRepresentation(input: {
    originalPath: string
    previewPath: string
    preview: boolean
    method: "HEAD" | "GET"
    load: (path: string) => Promise<Response>
    prepare: () => Promise<boolean | Response>
}) {
    let deliveryPath = input.preview ? input.previewPath : input.originalPath
    let response = await input.load(deliveryPath)
    if (input.preview && response.status === 404) {
        await response.body?.cancel()
        // A HEAD never creates an object. A legacy GET can repair a missing
        // derivative, but preparation failure must not hide the stored original.
        const prepared = input.method === "GET" && await input.prepare().catch(() => false)
        deliveryPath = prepared ? input.previewPath : input.originalPath
        // Newly generated bytes are already in memory. Do not download the
        // derivative again after storing it. Each caller gets its own response.
        response = prepared instanceof Response ? prepared : await input.load(deliveryPath)
    }
    return { response, deliveryPath }
}
